// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hawkeye_register/hawkeye_register.proto

package hawkeye_register

import (
	context "context"
	fmt "fmt"
	client "git.dhgames.cn/svr_comm/gmoss/v3/client"
	global "git.dhgames.cn/svr_comm/gmoss/v3/global"
	moss_rpc "git.dhgames.cn/svr_comm/gmoss/v3/moss_rpc"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Register_Subject int32

const (
	Register_Account Register_Subject = 0
	Register_Role    Register_Subject = 1
)

var Register_Subject_name = map[int32]string{
	0: "Account",
	1: "Role",
}

var Register_Subject_value = map[string]int32{
	"Account": 0,
	"Role":    1,
}

func (x Register_Subject) String() string {
	return proto.EnumName(Register_Subject_name, int32(x))
}

func (Register_Subject) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82df0a7b4110df97, []int{0, 0}
}

type Register struct {
	GameCd               string           `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Subject              Register_Subject `protobuf:"varint,2,opt,name=subject,proto3,enum=hawkeye_register.Register_Subject" json:"subject,omitempty"`
	DeviceInfo           *DeviceInfo      `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	UserInfo             *UserInfo        `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_82df0a7b4110df97, []int{0}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *Register) GetSubject() Register_Subject {
	if m != nil {
		return m.Subject
	}
	return Register_Account
}

func (m *Register) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *Register) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type DeviceInfo struct {
	Adid                 string   `protobuf:"bytes,1,opt,name=adid,proto3" json:"adid,omitempty"`
	Idfv                 string   `protobuf:"bytes,2,opt,name=idfv,proto3" json:"idfv,omitempty"`
	SmId                 string   `protobuf:"bytes,3,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	Imei                 string   `protobuf:"bytes,4,opt,name=imei,proto3" json:"imei,omitempty"`
	AndroidId            string   `protobuf:"bytes,5,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	AppsflyerId          string   `protobuf:"bytes,6,opt,name=appsflyer_id,json=appsflyerId,proto3" json:"appsflyer_id,omitempty"`
	Ip                   string   `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	DeviceToken          string   `protobuf:"bytes,8,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_82df0a7b4110df97, []int{1}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetAdid() string {
	if m != nil {
		return m.Adid
	}
	return ""
}

func (m *DeviceInfo) GetIdfv() string {
	if m != nil {
		return m.Idfv
	}
	return ""
}

func (m *DeviceInfo) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *DeviceInfo) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *DeviceInfo) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *DeviceInfo) GetAppsflyerId() string {
	if m != nil {
		return m.AppsflyerId
	}
	return ""
}

func (m *DeviceInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DeviceInfo) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

type UserInfo struct {
	BundleId             string   `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	ServerId             string   `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Lv                   string   `protobuf:"bytes,5,opt,name=lv,proto3" json:"lv,omitempty"`
	Vip                  string   `protobuf:"bytes,6,opt,name=vip,proto3" json:"vip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_82df0a7b4110df97, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func (m *UserInfo) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetLv() string {
	if m != nil {
		return m.Lv
	}
	return ""
}

func (m *UserInfo) GetVip() string {
	if m != nil {
		return m.Vip
	}
	return ""
}

type RegisterResp struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Pass                 bool     `protobuf:"varint,2,opt,name=pass,proto3" json:"pass,omitempty"`
	ErrCode              string   `protobuf:"bytes,3,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82df0a7b4110df97, []int{3}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *RegisterResp) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

func (m *RegisterResp) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *RegisterResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("hawkeye_register.Register_Subject", Register_Subject_name, Register_Subject_value)
	proto.RegisterType((*Register)(nil), "hawkeye_register.register")
	proto.RegisterType((*DeviceInfo)(nil), "hawkeye_register.deviceInfo")
	proto.RegisterType((*UserInfo)(nil), "hawkeye_register.userInfo")
	proto.RegisterType((*RegisterResp)(nil), "hawkeye_register.register_resp")
}

func init() {
	proto.RegisterFile("hawkeye_register/hawkeye_register.proto", fileDescriptor_82df0a7b4110df97)
}

var fileDescriptor_82df0a7b4110df97 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x69, 0xea, 0x8f, 0x09, 0x54, 0xd1, 0x70, 0xa8, 0x09, 0x20, 0x82, 0x2f, 0xe4, 0x54,
	0xa4, 0x70, 0xe0, 0x02, 0x07, 0xd4, 0x93, 0x0f, 0x08, 0xc9, 0x70, 0xb7, 0x1c, 0xef, 0x24, 0x6c,
	0x6b, 0x7b, 0xcd, 0xae, 0x6d, 0xd4, 0x9f, 0xc2, 0xdf, 0xe2, 0xef, 0x70, 0x41, 0xfb, 0xe1, 0xb4,
	0x8a, 0xd5, 0xdb, 0xec, 0x9b, 0xf7, 0xbc, 0xef, 0x8d, 0x67, 0xe1, 0xdd, 0xcf, 0xe2, 0xf7, 0x2d,
	0xdd, 0x51, 0x2e, 0xe9, 0xc0, 0x55, 0x47, 0xf2, 0xfd, 0x29, 0x70, 0xd5, 0x4a, 0xd1, 0x09, 0x5c,
	0x9e, 0xe2, 0xc9, 0x3f, 0x0f, 0xc2, 0xf1, 0x80, 0x97, 0x10, 0x1c, 0x8a, 0x9a, 0xf2, 0x92, 0xc5,
	0xde, 0xda, 0xdb, 0x44, 0x99, 0xaf, 0x8f, 0xd7, 0x0c, 0x3f, 0x41, 0xa0, 0xfa, 0xdd, 0x0d, 0x95,
	0x5d, 0x3c, 0x5b, 0x7b, 0x9b, 0x8b, 0x6d, 0x72, 0x35, 0xb9, 0xe1, 0x58, 0x7c, 0xb7, 0xcc, 0x6c,
	0x94, 0xe0, 0x67, 0x58, 0x30, 0x1a, 0x78, 0x49, 0x39, 0x6f, 0xf6, 0x22, 0x3e, 0x5b, 0x7b, 0x9b,
	0xc5, 0xf6, 0xd5, 0xf4, 0x0b, 0x96, 0x94, 0x36, 0x7b, 0x91, 0xc1, 0x7d, 0x8d, 0x1f, 0x21, 0xea,
	0x15, 0x49, 0x2b, 0x9e, 0x1b, 0xf1, 0x6a, 0x2a, 0xd6, 0x14, 0x23, 0x0d, 0xc7, 0x2a, 0x59, 0x43,
	0xe0, 0xbc, 0xe0, 0x02, 0x82, 0x2f, 0x65, 0x29, 0xfa, 0xa6, 0x5b, 0x3e, 0xc1, 0x10, 0xe6, 0x99,
	0xa8, 0x68, 0xe9, 0x25, 0x7f, 0x3d, 0x78, 0x78, 0x13, 0xc2, 0xbc, 0x60, 0x7c, 0x0c, 0x6f, 0x6a,
	0x8d, 0x71, 0xb6, 0x1f, 0x4c, 0xee, 0x28, 0x33, 0x35, 0x3e, 0x87, 0x73, 0x55, 0xe7, 0x9c, 0x99,
	0x28, 0x51, 0x36, 0x57, 0x75, 0x6a, 0x89, 0x35, 0x71, 0xe3, 0x50, 0x13, 0x6b, 0xe2, 0xf8, 0x1a,
	0xa0, 0x68, 0x98, 0x14, 0x9c, 0x69, 0xf6, 0xb9, 0xe9, 0x44, 0x0e, 0x49, 0x19, 0xbe, 0x85, 0xa7,
	0x45, 0xdb, 0xaa, 0x7d, 0x75, 0xa7, 0xe3, 0xb1, 0xd8, 0x37, 0x84, 0xc5, 0x11, 0x4b, 0x19, 0x5e,
	0xc0, 0x8c, 0xb7, 0x71, 0x60, 0x1a, 0x33, 0xde, 0x6a, 0x89, 0x9b, 0x65, 0x27, 0x6e, 0xa9, 0x89,
	0x43, 0x2b, 0xb1, 0xd8, 0x0f, 0x0d, 0x25, 0x7f, 0x3c, 0x38, 0xce, 0x00, 0x5f, 0x42, 0xb4, 0xeb,
	0x1b, 0x56, 0x51, 0x7e, 0xcc, 0x15, 0x5a, 0x20, 0x65, 0xba, 0xa9, 0x48, 0x0e, 0xf6, 0x72, 0x1b,
	0x30, 0xb4, 0x40, 0xca, 0xf4, 0x32, 0xd8, 0xb1, 0x8f, 0x31, 0x7d, 0xf3, 0x51, 0x86, 0x31, 0x04,
	0x85, 0x9d, 0xa5, 0xcb, 0x3a, 0x1e, 0xb5, 0xd9, 0x6a, 0x70, 0x31, 0x67, 0xd5, 0x80, 0x4b, 0x38,
	0x1b, 0x78, 0xeb, 0x62, 0xe9, 0x32, 0x19, 0xe0, 0xd9, 0xf8, 0xc7, 0x72, 0x49, 0xaa, 0xd5, 0x13,
	0x92, 0xf4, 0xab, 0x27, 0xd5, 0xdd, 0x1b, 0x8c, 0x1c, 0x62, 0x87, 0xda, 0x16, 0x4a, 0x19, 0x73,
	0x61, 0x66, 0x6a, 0x7c, 0x01, 0x21, 0x49, 0x99, 0x97, 0x82, 0x91, 0x73, 0x16, 0x90, 0x94, 0xd7,
	0x82, 0x91, 0xf6, 0xac, 0x5b, 0xb5, 0x3a, 0x38, 0x6b, 0x3e, 0x49, 0xf9, 0x55, 0x1d, 0xb6, 0x37,
	0x70, 0x79, 0xba, 0x31, 0xb9, 0x4d, 0x8a, 0xdf, 0x60, 0xf2, 0x2a, 0x70, 0xf5, 0xf8, 0x7a, 0xaf,
	0xde, 0x3c, 0xde, 0x33, 0x91, 0x76, 0xbe, 0x79, 0x6b, 0x1f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xa4, 0xaf, 0x82, 0xc7, 0x96, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// This is a compile-time assertion to ensure that this generated file
// is compatible with the moss package it is being compiled against.
const _ = moss_rpc.SupportPackageIsVersion3

func HawkeyeRegister(in *Register, opts *global.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := client.Send("hawkeye_register.hawkeye_register_server.hawkeye_register", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HawkeyeRegisterServerServer is the server API for HawkeyeRegisterServer service.
type HawkeyeRegisterServerServer interface {
	HawkeyeRegister(*Register) (*RegisterResp, error)
}

func RegisterHawkeyeRegisterServerServer(s *moss_rpc.Server, srv HawkeyeRegisterServerServer) {
	s.RegisterService(&HawkeyeRegisterServer_serviceDesc, srv)
}

func _HawkeyeRegisterServer_HawkeyeRegister_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(Register)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(HawkeyeRegisterServerServer).HawkeyeRegister(in)
}

var HawkeyeRegisterServer_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "hawkeye_register.hawkeye_register_server",
	HandlerType: (*HawkeyeRegisterServerServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "hawkeye_register",
			Handler:    _HawkeyeRegisterServer_HawkeyeRegister_Handler,
		},
	},
	Metadata: "hawkeye_register/hawkeye_register.proto",
}
