// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hawkeye_login/hawkeye_login.proto

package hawkeye_login

import (
	context "context"
	fmt "fmt"
	client "git.dhgames.cn/svr_comm/gmoss/v2/client"
	global "git.dhgames.cn/svr_comm/gmoss/v2/global"
	moss_rpc "git.dhgames.cn/svr_comm/gmoss/v2/moss_rpc"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Login_Subject int32

const (
	Login_Account Login_Subject = 0
	Login_Role    Login_Subject = 1
)

var Login_Subject_name = map[int32]string{
	0: "Account",
	1: "Role",
}

var Login_Subject_value = map[string]int32{
	"Account": 0,
	"Role":    1,
}

func (x Login_Subject) String() string {
	return proto.EnumName(Login_Subject_name, int32(x))
}

func (Login_Subject) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6896ccb986db1867, []int{0, 0}
}

// 部分字段，鹰眼不会用到，但是需要转发给BI进行计算，这部分字段详细详细含义可参考文档: https://www.yuque.com/docs/share/bb3ed862-ce1c-4da1-aea1-e14bc18687ee?#toc5 2020/12/18时注释
type Login struct {
	GameCd               string        `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Subject              Login_Subject `protobuf:"varint,2,opt,name=subject,proto3,enum=hawkeye_login.Login_Subject" json:"subject,omitempty"`
	DeviceInfo           *DeviceInfo   `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	UserInfo             *UserInfo     `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_6896ccb986db1867, []int{0}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *Login) GetSubject() Login_Subject {
	if m != nil {
		return m.Subject
	}
	return Login_Account
}

func (m *Login) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *Login) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type DeviceInfo struct {
	Adid                 string   `protobuf:"bytes,1,opt,name=adid,proto3" json:"adid,omitempty"`
	Idfv                 string   `protobuf:"bytes,2,opt,name=idfv,proto3" json:"idfv,omitempty"`
	SmId                 string   `protobuf:"bytes,3,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	Imei                 string   `protobuf:"bytes,4,opt,name=imei,proto3" json:"imei,omitempty"`
	AndroidId            string   `protobuf:"bytes,5,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	AppsflyerId          string   `protobuf:"bytes,6,opt,name=appsflyer_id,json=appsflyerId,proto3" json:"appsflyer_id,omitempty"`
	Ip                   string   `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	DeviceToken          string   `protobuf:"bytes,8,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6896ccb986db1867, []int{1}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetAdid() string {
	if m != nil {
		return m.Adid
	}
	return ""
}

func (m *DeviceInfo) GetIdfv() string {
	if m != nil {
		return m.Idfv
	}
	return ""
}

func (m *DeviceInfo) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *DeviceInfo) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *DeviceInfo) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *DeviceInfo) GetAppsflyerId() string {
	if m != nil {
		return m.AppsflyerId
	}
	return ""
}

func (m *DeviceInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DeviceInfo) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

type UserInfo struct {
	BundleId             string   `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	ServerId             string   `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Lv                   string   `protobuf:"bytes,5,opt,name=lv,proto3" json:"lv,omitempty"`
	Vip                  string   `protobuf:"bytes,6,opt,name=vip,proto3" json:"vip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6896ccb986db1867, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func (m *UserInfo) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetLv() string {
	if m != nil {
		return m.Lv
	}
	return ""
}

func (m *UserInfo) GetVip() string {
	if m != nil {
		return m.Vip
	}
	return ""
}

type LoginResp struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Pass                 bool     `protobuf:"varint,2,opt,name=pass,proto3" json:"pass,omitempty"`
	ErrCode              string   `protobuf:"bytes,3,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6896ccb986db1867, []int{3}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *LoginResp) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

func (m *LoginResp) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *LoginResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("hawkeye_login.Login_Subject", Login_Subject_name, Login_Subject_value)
	proto.RegisterType((*Login)(nil), "hawkeye_login.login")
	proto.RegisterType((*DeviceInfo)(nil), "hawkeye_login.deviceInfo")
	proto.RegisterType((*UserInfo)(nil), "hawkeye_login.userInfo")
	proto.RegisterType((*LoginResp)(nil), "hawkeye_login.login_resp")
}

func init() {
	proto.RegisterFile("hawkeye_login/hawkeye_login.proto", fileDescriptor_6896ccb986db1867)
}

var fileDescriptor_6896ccb986db1867 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x69, 0xe2, 0x8f, 0x09, 0x54, 0xd1, 0x50, 0xa9, 0x0e, 0x1f, 0x52, 0xea, 0x53, 0x4e,
	0x45, 0x0a, 0x88, 0x03, 0x27, 0x50, 0x4f, 0x3e, 0x70, 0x31, 0x1c, 0xb8, 0x59, 0x8e, 0x77, 0x12,
	0x96, 0xda, 0x5e, 0xb3, 0x6b, 0x1b, 0xf5, 0xa7, 0xf0, 0xb7, 0xf8, 0x1d, 0xfc, 0x08, 0xb4, 0x1f,
	0x4e, 0x71, 0xd5, 0x4b, 0x34, 0xfb, 0xe6, 0xbd, 0xdd, 0xf7, 0x26, 0x63, 0xb8, 0xfa, 0x5e, 0xfc,
	0xba, 0xa5, 0x3b, 0xca, 0x2b, 0x71, 0xe4, 0xcd, 0x9b, 0xc9, 0xe9, 0xba, 0x95, 0xa2, 0x13, 0xf8,
	0x6c, 0x02, 0x26, 0x7f, 0x3d, 0x58, 0x98, 0x0a, 0x2f, 0x21, 0x38, 0x16, 0x35, 0xe5, 0x25, 0x8b,
	0xbd, 0x8d, 0xb7, 0x8d, 0x32, 0x5f, 0x1f, 0x6f, 0x18, 0xbe, 0x87, 0x40, 0xf5, 0xfb, 0x1f, 0x54,
	0x76, 0xf1, 0x6c, 0xe3, 0x6d, 0xcf, 0x77, 0xaf, 0xae, 0xa7, 0x17, 0xdb, 0xdf, 0x2f, 0x96, 0x93,
	0x8d, 0x64, 0xfc, 0x00, 0x4b, 0x46, 0x03, 0x2f, 0x29, 0xe7, 0xcd, 0x41, 0xc4, 0x67, 0x1b, 0x6f,
	0xbb, 0xdc, 0xad, 0x1f, 0x68, 0x2d, 0x23, 0x6d, 0x0e, 0x22, 0x83, 0xfb, 0x1a, 0xdf, 0x41, 0xd4,
	0x2b, 0x92, 0x56, 0x39, 0x37, 0xca, 0xcb, 0x07, 0x4a, 0xdd, 0x37, 0xba, 0x70, 0xac, 0x92, 0x0d,
	0x04, 0xce, 0x05, 0x2e, 0x21, 0xf8, 0x54, 0x96, 0xa2, 0x6f, 0xba, 0xd5, 0x13, 0x0c, 0x61, 0x9e,
	0x89, 0x8a, 0x56, 0x5e, 0xf2, 0xc7, 0x83, 0xff, 0x9f, 0x41, 0x98, 0x17, 0x8c, 0x8f, 0x81, 0x4d,
	0xad, 0x31, 0xce, 0x0e, 0x83, 0xc9, 0x1a, 0x65, 0xa6, 0xc6, 0xe7, 0xb0, 0x50, 0x75, 0xce, 0x99,
	0x09, 0x11, 0x65, 0x73, 0x55, 0xa7, 0x96, 0x58, 0x13, 0x37, 0xf6, 0x34, 0xb1, 0x26, 0x8e, 0xaf,
	0x01, 0x8a, 0x86, 0x49, 0xc1, 0x99, 0x66, 0x2f, 0x4c, 0x27, 0x72, 0x48, 0xca, 0xf0, 0x0a, 0x9e,
	0x16, 0x6d, 0xab, 0x0e, 0xd5, 0x9d, 0xce, 0xc6, 0x62, 0xdf, 0x10, 0x96, 0x27, 0x2c, 0x65, 0x78,
	0x0e, 0x33, 0xde, 0xc6, 0x81, 0x69, 0xcc, 0x78, 0xab, 0x25, 0x6e, 0x8a, 0x9d, 0xb8, 0xa5, 0x26,
	0x0e, 0xad, 0xc4, 0x62, 0x5f, 0x35, 0x94, 0xfc, 0xf6, 0xe0, 0x34, 0x03, 0x7c, 0x09, 0xd1, 0xbe,
	0x6f, 0x58, 0x45, 0xf9, 0x29, 0x57, 0x68, 0x81, 0x94, 0xe9, 0xa6, 0x22, 0x39, 0xd8, 0xc7, 0x6d,
	0xc0, 0xd0, 0x02, 0x29, 0xd3, 0x0b, 0x60, 0x67, 0x3e, 0xc6, 0xf4, 0xcd, 0xa5, 0x0c, 0x63, 0x08,
	0x0a, 0x3b, 0x4b, 0x97, 0x75, 0x3c, 0x6a, 0xb3, 0xd5, 0xe0, 0x62, 0xce, 0xaa, 0x01, 0x57, 0x70,
	0x36, 0xf0, 0xd6, 0xc5, 0xd2, 0x65, 0xa2, 0x00, 0xcc, 0xdf, 0x95, 0x4b, 0x52, 0xad, 0x1e, 0x8f,
	0xa4, 0x9f, 0x3d, 0xa9, 0xee, 0xde, 0x5d, 0xe4, 0x10, 0x3b, 0xd1, 0xb6, 0x50, 0xca, 0x38, 0x0b,
	0x33, 0x53, 0xe3, 0x1a, 0x42, 0x92, 0x32, 0x2f, 0x05, 0x23, 0x67, 0x2b, 0x20, 0x29, 0x6f, 0x04,
	0x23, 0x6d, 0x58, 0xb7, 0x6a, 0x75, 0x74, 0xbe, 0x7c, 0x92, 0xf2, 0xb3, 0x3a, 0xee, 0xbe, 0xc1,
	0xc5, 0x64, 0x57, 0x72, 0x9b, 0x11, 0x3f, 0xc2, 0x74, 0xfb, 0xf1, 0xe2, 0xb1, 0x4d, 0x7e, 0xb1,
	0x7e, 0x0c, 0x35, 0x01, 0xf6, 0xbe, 0xf9, 0x88, 0xde, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xcc,
	0x90, 0x31, 0x22, 0x69, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// This is a compile-time assertion to ensure that this generated file
// is compatible with the moss package it is being compiled against.
const _ = moss_rpc.SupportPackageIsVersion3

func HawkeyeLogin(svr global.Cluster, in *Login, callType global.CallType, opts global.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := client.Send(svr, callType, "hawkeye_login.hawkeye_login_server.hawkeye_login", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HawkeyeLoginServerServer is the server API for HawkeyeLoginServer service.
type HawkeyeLoginServerServer interface {
	HawkeyeLogin(*Login) (*LoginResp, error)
}

func RegisterHawkeyeLoginServerServer(s *moss_rpc.Server, srv HawkeyeLoginServerServer) {
	s.RegisterService(&HawkeyeLoginServer_serviceDesc, srv)
}

func _HawkeyeLoginServer_HawkeyeLogin_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(Login)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(HawkeyeLoginServerServer).HawkeyeLogin(in)
}

var HawkeyeLoginServer_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "hawkeye_login.hawkeye_login_server",
	HandlerType: (*HawkeyeLoginServerServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "hawkeye_login",
			Handler:    _HawkeyeLoginServer_HawkeyeLogin_Handler,
		},
	},
	Metadata: "hawkeye_login/hawkeye_login.proto",
}
