// Code generated by protoc-gen-go. DO NOT EDIT.
// source: glogin/glogin.proto

package glogin

import (
	context "context"
	fmt "fmt"
	client "git.dhgames.cn/svr_comm/gmoss/v2/client"
	global "git.dhgames.cn/svr_comm/gmoss/v2/global"
	moss_rpc "git.dhgames.cn/svr_comm/gmoss/v2/moss_rpc"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Client信息
type LoginClient struct {
	Imei                 string   `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	AndroidId            string   `protobuf:"bytes,2,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	Dhid                 string   `protobuf:"bytes,3,opt,name=dhid,proto3" json:"dhid,omitempty"`
	MacAddress           string   `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	DeviceModel          string   `protobuf:"bytes,5,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	DviceName            string   `protobuf:"bytes,6,opt,name=dvice_name,json=dviceName,proto3" json:"dvice_name,omitempty"`
	OsVersion            string   `protobuf:"bytes,7,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	NetworkType          string   `protobuf:"bytes,8,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	Ip                   string   `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	Country              string   `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginClient) Reset()         { *m = LoginClient{} }
func (m *LoginClient) String() string { return proto.CompactTextString(m) }
func (*LoginClient) ProtoMessage()    {}
func (*LoginClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{0}
}

func (m *LoginClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginClient.Unmarshal(m, b)
}
func (m *LoginClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginClient.Marshal(b, m, deterministic)
}
func (m *LoginClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginClient.Merge(m, src)
}
func (m *LoginClient) XXX_Size() int {
	return xxx_messageInfo_LoginClient.Size(m)
}
func (m *LoginClient) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginClient.DiscardUnknown(m)
}

var xxx_messageInfo_LoginClient proto.InternalMessageInfo

func (m *LoginClient) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *LoginClient) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *LoginClient) GetDhid() string {
	if m != nil {
		return m.Dhid
	}
	return ""
}

func (m *LoginClient) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *LoginClient) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *LoginClient) GetDviceName() string {
	if m != nil {
		return m.DviceName
	}
	return ""
}

func (m *LoginClient) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *LoginClient) GetNetworkType() string {
	if m != nil {
		return m.NetworkType
	}
	return ""
}

func (m *LoginClient) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LoginClient) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

//Game信息
type LoginGame struct {
	Adid                 string   `protobuf:"bytes,1,opt,name=adid,proto3" json:"adid,omitempty"`
	Idfv                 string   `protobuf:"bytes,2,opt,name=idfv,proto3" json:"idfv,omitempty"`
	AppsflyerId          string   `protobuf:"bytes,3,opt,name=appsflyer_id,json=appsflyerId,proto3" json:"appsflyer_id,omitempty"`
	AdvertisingId        string   `protobuf:"bytes,4,opt,name=advertising_id,json=advertisingId,proto3" json:"advertising_id,omitempty"`
	DeviceToken          string   `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Reserved_2           string   `protobuf:"bytes,7,opt,name=reserved_2,json=reserved2,proto3" json:"reserved_2,omitempty"`
	BundleId             string   `protobuf:"bytes,8,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	AppVersion           string   `protobuf:"bytes,9,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Platform             string   `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel              string   `protobuf:"bytes,11,opt,name=channel,proto3" json:"channel,omitempty"`
	GameCd               string   `protobuf:"bytes,12,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginGame) Reset()         { *m = LoginGame{} }
func (m *LoginGame) String() string { return proto.CompactTextString(m) }
func (*LoginGame) ProtoMessage()    {}
func (*LoginGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{1}
}

func (m *LoginGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginGame.Unmarshal(m, b)
}
func (m *LoginGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginGame.Marshal(b, m, deterministic)
}
func (m *LoginGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginGame.Merge(m, src)
}
func (m *LoginGame) XXX_Size() int {
	return xxx_messageInfo_LoginGame.Size(m)
}
func (m *LoginGame) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginGame.DiscardUnknown(m)
}

var xxx_messageInfo_LoginGame proto.InternalMessageInfo

func (m *LoginGame) GetAdid() string {
	if m != nil {
		return m.Adid
	}
	return ""
}

func (m *LoginGame) GetIdfv() string {
	if m != nil {
		return m.Idfv
	}
	return ""
}

func (m *LoginGame) GetAppsflyerId() string {
	if m != nil {
		return m.AppsflyerId
	}
	return ""
}

func (m *LoginGame) GetAdvertisingId() string {
	if m != nil {
		return m.AdvertisingId
	}
	return ""
}

func (m *LoginGame) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *LoginGame) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *LoginGame) GetReserved_2() string {
	if m != nil {
		return m.Reserved_2
	}
	return ""
}

func (m *LoginGame) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func (m *LoginGame) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *LoginGame) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginGame) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *LoginGame) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

//第三方登录请求
type ThirdLoginReq struct {
	ThirdPlat            string       `protobuf:"bytes,1,opt,name=third_plat,json=thirdPlat,proto3" json:"third_plat,omitempty"`
	ThirdUid             string       `protobuf:"bytes,2,opt,name=third_uid,json=thirdUid,proto3" json:"third_uid,omitempty"`
	ThirdToken           string       `protobuf:"bytes,3,opt,name=third_token,json=thirdToken,proto3" json:"third_token,omitempty"`
	AccessToken          string       `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Client               *LoginClient `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,6,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ThirdLoginReq) Reset()         { *m = ThirdLoginReq{} }
func (m *ThirdLoginReq) String() string { return proto.CompactTextString(m) }
func (*ThirdLoginReq) ProtoMessage()    {}
func (*ThirdLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{2}
}

func (m *ThirdLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdLoginReq.Unmarshal(m, b)
}
func (m *ThirdLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdLoginReq.Marshal(b, m, deterministic)
}
func (m *ThirdLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdLoginReq.Merge(m, src)
}
func (m *ThirdLoginReq) XXX_Size() int {
	return xxx_messageInfo_ThirdLoginReq.Size(m)
}
func (m *ThirdLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdLoginReq proto.InternalMessageInfo

func (m *ThirdLoginReq) GetThirdPlat() string {
	if m != nil {
		return m.ThirdPlat
	}
	return ""
}

func (m *ThirdLoginReq) GetThirdUid() string {
	if m != nil {
		return m.ThirdUid
	}
	return ""
}

func (m *ThirdLoginReq) GetThirdToken() string {
	if m != nil {
		return m.ThirdToken
	}
	return ""
}

func (m *ThirdLoginReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ThirdLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *ThirdLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//第三方登录返回
type ThridLoginRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string   `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	ThirdUid             string   `protobuf:"bytes,3,opt,name=third_uid,json=thirdUid,proto3" json:"third_uid,omitempty"`
	Errmsg               string   `protobuf:"bytes,4,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string   `protobuf:"bytes,5,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            string   `protobuf:"bytes,6,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThridLoginRsp) Reset()         { *m = ThridLoginRsp{} }
func (m *ThridLoginRsp) String() string { return proto.CompactTextString(m) }
func (*ThridLoginRsp) ProtoMessage()    {}
func (*ThridLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{3}
}

func (m *ThridLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThridLoginRsp.Unmarshal(m, b)
}
func (m *ThridLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThridLoginRsp.Marshal(b, m, deterministic)
}
func (m *ThridLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThridLoginRsp.Merge(m, src)
}
func (m *ThridLoginRsp) XXX_Size() int {
	return xxx_messageInfo_ThridLoginRsp.Size(m)
}
func (m *ThridLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ThridLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ThridLoginRsp proto.InternalMessageInfo

func (m *ThridLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ThridLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *ThridLoginRsp) GetThirdUid() string {
	if m != nil {
		return m.ThirdUid
	}
	return ""
}

func (m *ThridLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *ThridLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *ThridLoginRsp) GetDhAccount() string {
	if m != nil {
		return m.DhAccount
	}
	return ""
}

//手机验证码登录请求
type SmsLoginReq struct {
	Step                 string       `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Phone                string       `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Verifycode           string       `protobuf:"bytes,3,opt,name=verifycode,proto3" json:"verifycode,omitempty"`
	Client               *LoginClient `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,5,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SmsLoginReq) Reset()         { *m = SmsLoginReq{} }
func (m *SmsLoginReq) String() string { return proto.CompactTextString(m) }
func (*SmsLoginReq) ProtoMessage()    {}
func (*SmsLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{4}
}

func (m *SmsLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsLoginReq.Unmarshal(m, b)
}
func (m *SmsLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsLoginReq.Marshal(b, m, deterministic)
}
func (m *SmsLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsLoginReq.Merge(m, src)
}
func (m *SmsLoginReq) XXX_Size() int {
	return xxx_messageInfo_SmsLoginReq.Size(m)
}
func (m *SmsLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_SmsLoginReq proto.InternalMessageInfo

func (m *SmsLoginReq) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *SmsLoginReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SmsLoginReq) GetVerifycode() string {
	if m != nil {
		return m.Verifycode
	}
	return ""
}

func (m *SmsLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *SmsLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//手机验证码登录返回
type SmsLoginRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string   `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string   `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            string   `protobuf:"bytes,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsLoginRsp) Reset()         { *m = SmsLoginRsp{} }
func (m *SmsLoginRsp) String() string { return proto.CompactTextString(m) }
func (*SmsLoginRsp) ProtoMessage()    {}
func (*SmsLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{5}
}

func (m *SmsLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsLoginRsp.Unmarshal(m, b)
}
func (m *SmsLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsLoginRsp.Marshal(b, m, deterministic)
}
func (m *SmsLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsLoginRsp.Merge(m, src)
}
func (m *SmsLoginRsp) XXX_Size() int {
	return xxx_messageInfo_SmsLoginRsp.Size(m)
}
func (m *SmsLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SmsLoginRsp proto.InternalMessageInfo

func (m *SmsLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SmsLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *SmsLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *SmsLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *SmsLoginRsp) GetDhAccount() string {
	if m != nil {
		return m.DhAccount
	}
	return ""
}

//游客登录请求参数
type VisitorLoginReq struct {
	Dhid                 string       `protobuf:"bytes,1,opt,name=dhid,proto3" json:"dhid,omitempty"`
	Client               *LoginClient `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VisitorLoginReq) Reset()         { *m = VisitorLoginReq{} }
func (m *VisitorLoginReq) String() string { return proto.CompactTextString(m) }
func (*VisitorLoginReq) ProtoMessage()    {}
func (*VisitorLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{6}
}

func (m *VisitorLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorLoginReq.Unmarshal(m, b)
}
func (m *VisitorLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorLoginReq.Marshal(b, m, deterministic)
}
func (m *VisitorLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorLoginReq.Merge(m, src)
}
func (m *VisitorLoginReq) XXX_Size() int {
	return xxx_messageInfo_VisitorLoginReq.Size(m)
}
func (m *VisitorLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorLoginReq proto.InternalMessageInfo

func (m *VisitorLoginReq) GetDhid() string {
	if m != nil {
		return m.Dhid
	}
	return ""
}

func (m *VisitorLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *VisitorLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//手机验证码登录返回
type VisitorLoginRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string   `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string   `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            string   `protobuf:"bytes,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitorLoginRsp) Reset()         { *m = VisitorLoginRsp{} }
func (m *VisitorLoginRsp) String() string { return proto.CompactTextString(m) }
func (*VisitorLoginRsp) ProtoMessage()    {}
func (*VisitorLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{7}
}

func (m *VisitorLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorLoginRsp.Unmarshal(m, b)
}
func (m *VisitorLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorLoginRsp.Marshal(b, m, deterministic)
}
func (m *VisitorLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorLoginRsp.Merge(m, src)
}
func (m *VisitorLoginRsp) XXX_Size() int {
	return xxx_messageInfo_VisitorLoginRsp.Size(m)
}
func (m *VisitorLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorLoginRsp proto.InternalMessageInfo

func (m *VisitorLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VisitorLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *VisitorLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *VisitorLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *VisitorLoginRsp) GetDhAccount() string {
	if m != nil {
		return m.DhAccount
	}
	return ""
}

//游客绑定申请
type VistorBindThridReq struct {
	Dhid                 string   `protobuf:"bytes,1,opt,name=dhid,proto3" json:"dhid,omitempty"`
	DhToken              string   `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Plat                 string   `protobuf:"bytes,3,opt,name=plat,proto3" json:"plat,omitempty"`
	ThridId              string   `protobuf:"bytes,4,opt,name=thridId,proto3" json:"thridId,omitempty"`
	Thridtoken           string   `protobuf:"bytes,5,opt,name=thridtoken,proto3" json:"thridtoken,omitempty"`
	Extra                string   `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	BundleId             string   `protobuf:"bytes,7,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VistorBindThridReq) Reset()         { *m = VistorBindThridReq{} }
func (m *VistorBindThridReq) String() string { return proto.CompactTextString(m) }
func (*VistorBindThridReq) ProtoMessage()    {}
func (*VistorBindThridReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{8}
}

func (m *VistorBindThridReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VistorBindThridReq.Unmarshal(m, b)
}
func (m *VistorBindThridReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VistorBindThridReq.Marshal(b, m, deterministic)
}
func (m *VistorBindThridReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VistorBindThridReq.Merge(m, src)
}
func (m *VistorBindThridReq) XXX_Size() int {
	return xxx_messageInfo_VistorBindThridReq.Size(m)
}
func (m *VistorBindThridReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VistorBindThridReq.DiscardUnknown(m)
}

var xxx_messageInfo_VistorBindThridReq proto.InternalMessageInfo

func (m *VistorBindThridReq) GetDhid() string {
	if m != nil {
		return m.Dhid
	}
	return ""
}

func (m *VistorBindThridReq) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *VistorBindThridReq) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

func (m *VistorBindThridReq) GetThridId() string {
	if m != nil {
		return m.ThridId
	}
	return ""
}

func (m *VistorBindThridReq) GetThridtoken() string {
	if m != nil {
		return m.Thridtoken
	}
	return ""
}

func (m *VistorBindThridReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *VistorBindThridReq) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

//游客绑定回复
type VistorBindThridRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string   `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string   `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            string   `protobuf:"bytes,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VistorBindThridRsp) Reset()         { *m = VistorBindThridRsp{} }
func (m *VistorBindThridRsp) String() string { return proto.CompactTextString(m) }
func (*VistorBindThridRsp) ProtoMessage()    {}
func (*VistorBindThridRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{9}
}

func (m *VistorBindThridRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VistorBindThridRsp.Unmarshal(m, b)
}
func (m *VistorBindThridRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VistorBindThridRsp.Marshal(b, m, deterministic)
}
func (m *VistorBindThridRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VistorBindThridRsp.Merge(m, src)
}
func (m *VistorBindThridRsp) XXX_Size() int {
	return xxx_messageInfo_VistorBindThridRsp.Size(m)
}
func (m *VistorBindThridRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VistorBindThridRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VistorBindThridRsp proto.InternalMessageInfo

func (m *VistorBindThridRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *VistorBindThridRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *VistorBindThridRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *VistorBindThridRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *VistorBindThridRsp) GetDhAccount() string {
	if m != nil {
		return m.DhAccount
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginClient)(nil), "glogin.LoginClient")
	proto.RegisterType((*LoginGame)(nil), "glogin.LoginGame")
	proto.RegisterType((*ThirdLoginReq)(nil), "glogin.ThirdLoginReq")
	proto.RegisterType((*ThridLoginRsp)(nil), "glogin.ThridLoginRsp")
	proto.RegisterType((*SmsLoginReq)(nil), "glogin.SmsLoginReq")
	proto.RegisterType((*SmsLoginRsp)(nil), "glogin.SmsLoginRsp")
	proto.RegisterType((*VisitorLoginReq)(nil), "glogin.VisitorLoginReq")
	proto.RegisterType((*VisitorLoginRsp)(nil), "glogin.VisitorLoginRsp")
	proto.RegisterType((*VistorBindThridReq)(nil), "glogin.VistorBindThridReq")
	proto.RegisterType((*VistorBindThridRsp)(nil), "glogin.VistorBindThridRsp")
}

func init() {
	proto.RegisterFile("glogin/glogin.proto", fileDescriptor_81471964e5a3cd05)
}

var fileDescriptor_81471964e5a3cd05 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x96, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0xc7, 0xe5, 0xc4, 0x4e, 0xe2, 0xf2, 0xee, 0x22, 0x7a, 0x80, 0x35, 0x41, 0x7c, 0x45, 0x5a,
	0x09, 0x09, 0x69, 0x57, 0x0a, 0xe2, 0xc4, 0x69, 0x98, 0x03, 0x8a, 0x60, 0x10, 0xca, 0x0c, 0x73,
	0xb5, 0x7a, 0xdc, 0x1d, 0xbb, 0x35, 0xb6, 0xbb, 0xe9, 0x76, 0x02, 0x79, 0x03, 0x0e, 0x48, 0x3c,
	0x04, 0x07, 0x0e, 0xf0, 0x18, 0xbc, 0x09, 0x17, 0x1e, 0x03, 0x75, 0x75, 0xdb, 0xe3, 0x84, 0x99,
	0xd1, 0x70, 0x81, 0xd3, 0x56, 0xfd, 0xab, 0xe2, 0xae, 0xfa, 0x75, 0x75, 0xed, 0xc0, 0x49, 0x51,
	0xc9, 0x42, 0x34, 0xaf, 0xdc, 0x3f, 0x2f, 0x95, 0x96, 0xad, 0x24, 0x13, 0xe7, 0x2d, 0x7e, 0x19,
	0x41, 0xf2, 0x95, 0xb5, 0xce, 0x2a, 0xc1, 0x9b, 0x96, 0x10, 0x08, 0x45, 0xcd, 0x45, 0x1a, 0x7c,
	0x10, 0x7c, 0x14, 0xaf, 0xd1, 0x26, 0xef, 0x02, 0xd0, 0x86, 0x69, 0x29, 0x58, 0x26, 0x58, 0x3a,
	0xc2, 0x48, 0xec, 0x95, 0x15, 0xb3, 0x3f, 0x61, 0xa5, 0x60, 0xe9, 0xd8, 0xfd, 0xc4, 0xda, 0xe4,
	0x7d, 0x48, 0x6a, 0x9a, 0x67, 0x94, 0x31, 0xcd, 0x8d, 0x49, 0x43, 0x0c, 0x41, 0x4d, 0xf3, 0x53,
	0xa7, 0x90, 0x0f, 0xe1, 0x09, 0xe3, 0x3b, 0x91, 0xf3, 0xac, 0x96, 0x8c, 0x57, 0x69, 0x84, 0x19,
	0x89, 0xd3, 0xce, 0xad, 0x64, 0x8f, 0x65, 0x98, 0xd1, 0xd0, 0x9a, 0xa7, 0x13, 0x77, 0x2c, 0x2a,
	0x5f, 0xd3, 0x9a, 0xdb, 0xb0, 0x34, 0xd9, 0x8e, 0x6b, 0x23, 0x64, 0x93, 0x4e, 0x5d, 0x58, 0x9a,
	0x2b, 0x27, 0xd8, 0x03, 0x1a, 0xde, 0x7e, 0x2f, 0xf5, 0x4d, 0xd6, 0xee, 0x15, 0x4f, 0x67, 0xee,
	0x00, 0xaf, 0x5d, 0xee, 0x15, 0x27, 0xcf, 0x60, 0x24, 0x54, 0x1a, 0x63, 0x60, 0x24, 0x14, 0x49,
	0x61, 0x9a, 0xcb, 0x6d, 0xd3, 0xea, 0x7d, 0x0a, 0x28, 0x76, 0xee, 0xe2, 0xaf, 0x11, 0xc4, 0x48,
	0xe9, 0x0b, 0x7b, 0x32, 0x81, 0x90, 0x32, 0xc1, 0x3a, 0x46, 0xd6, 0x46, 0x6e, 0x6c, 0xb3, 0xf3,
	0x74, 0xd0, 0xb6, 0x25, 0x50, 0xa5, 0xcc, 0xa6, 0xda, 0x73, 0x9d, 0xf5, 0x80, 0x92, 0x5e, 0x5b,
	0x31, 0xf2, 0x02, 0x9e, 0x51, 0xb6, 0xe3, 0xba, 0x15, 0x46, 0x34, 0x85, 0x4d, 0x72, 0xa8, 0x9e,
	0x0e, 0xd4, 0x15, 0x1b, 0xd0, 0x6a, 0xe5, 0x0d, 0x6f, 0x0e, 0x69, 0x5d, 0x5a, 0x89, 0xcc, 0x61,
	0x56, 0xd1, 0xa6, 0xd8, 0xd2, 0xa2, 0x63, 0xd5, 0xfb, 0x16, 0x95, 0xe6, 0x86, 0xeb, 0x1d, 0x67,
	0xd9, 0xb2, 0x43, 0xd5, 0x29, 0x4b, 0xf2, 0x0e, 0xc4, 0xd7, 0xdb, 0x86, 0x55, 0xdc, 0x9e, 0xef,
	0x38, 0xcd, 0x9c, 0xb0, 0xc2, 0x9b, 0xa4, 0x4a, 0xf5, 0x9c, 0x1d, 0x2d, 0xa0, 0x4a, 0x75, 0xa0,
	0xe7, 0x30, 0x53, 0x15, 0x6d, 0x37, 0x52, 0xd7, 0x1e, 0x5b, 0xef, 0x23, 0xd1, 0x92, 0x36, 0x0d,
	0xaf, 0xd2, 0xc4, 0x13, 0x75, 0x2e, 0x79, 0x0e, 0xd3, 0x82, 0xd6, 0x3c, 0xcb, 0x59, 0xfa, 0x04,
	0x23, 0x13, 0xeb, 0x9e, 0xb1, 0xc5, 0x9f, 0x01, 0x3c, 0xbd, 0x2c, 0x85, 0x66, 0xc8, 0x7b, 0xcd,
	0xbf, 0xb3, 0xd5, 0xb7, 0x56, 0xc8, 0xec, 0x67, 0x3d, 0xf4, 0x18, 0x95, 0x6f, 0x2a, 0xda, 0xda,
	0xea, 0x5d, 0x78, 0xdb, 0x0f, 0xe7, 0x0c, 0x85, 0x6f, 0xdd, 0x1c, 0xba, 0xa0, 0xe3, 0xe6, 0x6e,
	0xc0, 0x7d, 0xce, 0x61, 0xb3, 0x77, 0x94, 0xe7, 0xdc, 0x18, 0x9f, 0x11, 0xfa, 0x3b, 0x42, 0xcd,
	0xa5, 0x7c, 0x0c, 0x93, 0x1c, 0x1f, 0x07, 0x62, 0x4f, 0x96, 0x27, 0x2f, 0xfd, 0x4b, 0x1a, 0xbc,
	0x9b, 0xb5, 0x4f, 0x21, 0x2f, 0x20, 0x2c, 0xba, 0x71, 0x4d, 0x96, 0xaf, 0x1f, 0xa4, 0xda, 0xe1,
	0x59, 0x63, 0x78, 0xf1, 0x2b, 0x76, 0xa9, 0x85, 0xef, 0xd2, 0x28, 0x3b, 0x40, 0xb9, 0x64, 0x1c,
	0xfb, 0x8b, 0xd6, 0x68, 0x93, 0xb7, 0x61, 0xc6, 0x4a, 0x5f, 0x98, 0xeb, 0x6c, 0xca, 0x4a, 0x57,
	0xd4, 0x41, 0xd7, 0xe3, 0xa3, 0xae, 0xdf, 0x82, 0x09, 0xd7, 0xba, 0x36, 0x85, 0x6f, 0xc7, 0x7b,
	0xe4, 0x04, 0x22, 0x53, 0xdb, 0x4b, 0x76, 0xf3, 0x13, 0x9a, 0x7a, 0xc5, 0xf0, 0x99, 0x95, 0x19,
	0xcd, 0x71, 0xd6, 0xfb, 0x67, 0x56, 0x9e, 0x3a, 0x61, 0xf1, 0x5b, 0x00, 0xc9, 0x45, 0x6d, 0xfa,
	0xdb, 0x20, 0x10, 0x9a, 0x96, 0xab, 0x6e, 0xf8, 0xad, 0x4d, 0xde, 0x80, 0x48, 0x95, 0xb2, 0xe1,
	0xbe, 0x48, 0xe7, 0x90, 0xf7, 0x00, 0x76, 0x5c, 0x8b, 0xcd, 0x1e, 0xfb, 0xf2, 0xe8, 0x6f, 0x95,
	0x01, 0xd7, 0xf0, 0xf1, 0x5c, 0xa3, 0x87, 0xb9, 0xfe, 0x38, 0xac, 0xf6, 0xdf, 0x53, 0xbd, 0x05,
	0x37, 0xbe, 0x1b, 0x5c, 0x78, 0x2f, 0xb8, 0xe8, 0x18, 0xdc, 0x1e, 0x5e, 0xbb, 0x12, 0x46, 0xb4,
	0x52, 0x0f, 0xd9, 0xe1, 0xa6, 0x0c, 0x06, 0x9b, 0xf2, 0x96, 0xc2, 0xe8, 0xf1, 0x14, 0xc6, 0x0f,
	0x53, 0xf8, 0x29, 0x38, 0x3a, 0xfb, 0xff, 0x25, 0xf1, 0x47, 0x00, 0xe4, 0x4a, 0x98, 0x56, 0xea,
	0xcf, 0x45, 0xc3, 0x70, 0xec, 0xef, 0xa3, 0xf1, 0x40, 0x45, 0x04, 0x42, 0x5c, 0x00, 0xfe, 0xbf,
	0x19, 0x6b, 0xdb, 0xfd, 0xd2, 0xda, 0xcf, 0xad, 0xba, 0x7a, 0x3a, 0xd7, 0x0e, 0x1f, 0x9a, 0xc3,
	0x7d, 0x39, 0x50, 0xec, 0xc8, 0xf2, 0x1f, 0x5a, 0x4d, 0xfd, 0xc0, 0x3b, 0xe7, 0x70, 0x13, 0x4e,
	0x0f, 0x37, 0xe1, 0xe2, 0xe7, 0x3b, 0xda, 0x38, 0x02, 0x1b, 0xff, 0xa7, 0x60, 0x97, 0xbf, 0x07,
	0x10, 0xe1, 0x05, 0x93, 0x57, 0x30, 0xbe, 0x38, 0xbf, 0x20, 0xfd, 0xf0, 0x0c, 0x5e, 0xec, 0xfc,
	0x9f, 0xa2, 0x51, 0xe4, 0x53, 0x88, 0x70, 0xcb, 0x92, 0x37, 0xbb, 0xe8, 0xc1, 0xd2, 0x9d, 0x0f,
	0xe4, 0xe1, 0x96, 0xfa, 0x0c, 0xa6, 0x7e, 0xb0, 0xc8, 0xf3, 0x2e, 0xe3, 0x68, 0xca, 0xe7, 0x77,
	0x07, 0x8c, 0x5a, 0x7e, 0x09, 0xa1, 0x25, 0x47, 0xce, 0x20, 0x76, 0x04, 0xed, 0xf9, 0xf3, 0x41,
	0xf6, 0xd1, 0x84, 0xcc, 0xef, 0x8d, 0x19, 0x75, 0x3d, 0xc1, 0xbf, 0x63, 0x3e, 0xf9, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x70, 0x90, 0xa6, 0x97, 0xde, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// This is a compile-time assertion to ensure that this generated file
// is compatible with the moss package it is being compiled against.
const _ = moss_rpc.SupportPackageIsVersion3

func SMS(svr global.Cluster, in *SmsLoginReq, callType global.CallType, opts global.CallOption) (*SmsLoginRsp, error) {
	out := new(SmsLoginRsp)
	err := client.Send(svr, callType, "glogin.Login.SMS", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func Third(svr global.Cluster, in *ThirdLoginReq, callType global.CallType, opts global.CallOption) (*ThridLoginRsp, error) {
	out := new(ThridLoginRsp)
	err := client.Send(svr, callType, "glogin.Login.Third", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func Visitor(svr global.Cluster, in *VisitorLoginReq, callType global.CallType, opts global.CallOption) (*VisitorLoginRsp, error) {
	out := new(VisitorLoginRsp)
	err := client.Send(svr, callType, "glogin.Login.Visitor", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	SMS(*SmsLoginReq) (*SmsLoginRsp, error)
	Third(*ThirdLoginReq) (*ThridLoginRsp, error)
	Visitor(*VisitorLoginReq) (*VisitorLoginRsp, error)
}

func RegisterLoginServer(s *moss_rpc.Server, srv LoginServer) {
	s.RegisterService(&Login_serviceDesc, srv)
}

func _Login_SMS_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(SmsLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).SMS(in)
}

func _Login_Third_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(ThirdLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).Third(in)
}

func _Login_Visitor_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(VisitorLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).Visitor(in)
}

var Login_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "glogin.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "SMS",
			Handler:    _Login_SMS_Handler,
		},
		{
			MethodName: "Third",
			Handler:    _Login_Third_Handler,
		},
		{
			MethodName: "Visitor",
			Handler:    _Login_Visitor_Handler,
		},
	},
	Metadata: "glogin/glogin.proto",
}

func BindThird(svr global.Cluster, in *VistorBindThridReq, callType global.CallType, opts global.CallOption) (*VistorBindThridRsp, error) {
	out := new(VistorBindThridRsp)
	err := client.Send(svr, callType, "glogin.Bind.BindThird", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BindServer is the server API for Bind service.
type BindServer interface {
	BindThird(*VistorBindThridReq) (*VistorBindThridRsp, error)
}

func RegisterBindServer(s *moss_rpc.Server, srv BindServer) {
	s.RegisterService(&Bind_serviceDesc, srv)
}

func _Bind_BindThird_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(VistorBindThridReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(BindServer).BindThird(in)
}

var Bind_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "glogin.Bind",
	HandlerType: (*BindServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "BindThird",
			Handler:    _Bind_BindThird_Handler,
		},
	},
	Metadata: "glogin/glogin.proto",
}
