// Code generated by protoc-gen-go. DO NOT EDIT.
// source: glogin/glogin.proto

package glogin

import (
	context "context"
	fmt "fmt"
	client "git.dhgames.cn/svr_comm/gmoss/v3/client"
	global "git.dhgames.cn/svr_comm/gmoss/v3/global"
	moss_rpc "git.dhgames.cn/svr_comm/gmoss/v3/moss_rpc"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Client信息
type LoginClient struct {
	Imei                 string   `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	AndroidId            string   `protobuf:"bytes,2,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	Dhid                 string   `protobuf:"bytes,3,opt,name=dhid,proto3" json:"dhid,omitempty"`
	MacAddress           string   `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	DeviceModel          string   `protobuf:"bytes,5,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	DviceName            string   `protobuf:"bytes,6,opt,name=dvice_name,json=dviceName,proto3" json:"dvice_name,omitempty"`
	OsVersion            string   `protobuf:"bytes,7,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	NetworkType          string   `protobuf:"bytes,8,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	Ip                   string   `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	Country              string   `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginClient) Reset()         { *m = LoginClient{} }
func (m *LoginClient) String() string { return proto.CompactTextString(m) }
func (*LoginClient) ProtoMessage()    {}
func (*LoginClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{0}
}

func (m *LoginClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginClient.Unmarshal(m, b)
}
func (m *LoginClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginClient.Marshal(b, m, deterministic)
}
func (m *LoginClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginClient.Merge(m, src)
}
func (m *LoginClient) XXX_Size() int {
	return xxx_messageInfo_LoginClient.Size(m)
}
func (m *LoginClient) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginClient.DiscardUnknown(m)
}

var xxx_messageInfo_LoginClient proto.InternalMessageInfo

func (m *LoginClient) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *LoginClient) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *LoginClient) GetDhid() string {
	if m != nil {
		return m.Dhid
	}
	return ""
}

func (m *LoginClient) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *LoginClient) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *LoginClient) GetDviceName() string {
	if m != nil {
		return m.DviceName
	}
	return ""
}

func (m *LoginClient) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *LoginClient) GetNetworkType() string {
	if m != nil {
		return m.NetworkType
	}
	return ""
}

func (m *LoginClient) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LoginClient) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

//Game信息
type LoginGame struct {
	Adid                 string   `protobuf:"bytes,1,opt,name=adid,proto3" json:"adid,omitempty"`
	Idfv                 string   `protobuf:"bytes,2,opt,name=idfv,proto3" json:"idfv,omitempty"`
	AppsflyerId          string   `protobuf:"bytes,3,opt,name=appsflyer_id,json=appsflyerId,proto3" json:"appsflyer_id,omitempty"`
	AdvertisingId        string   `protobuf:"bytes,4,opt,name=advertising_id,json=advertisingId,proto3" json:"advertising_id,omitempty"`
	DeviceToken          string   `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Reserved_2           string   `protobuf:"bytes,7,opt,name=reserved_2,json=reserved2,proto3" json:"reserved_2,omitempty"`
	BundleId             string   `protobuf:"bytes,8,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	AppVersion           string   `protobuf:"bytes,9,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Platform             string   `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel              string   `protobuf:"bytes,11,opt,name=channel,proto3" json:"channel,omitempty"`
	GameCd               string   `protobuf:"bytes,12,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginGame) Reset()         { *m = LoginGame{} }
func (m *LoginGame) String() string { return proto.CompactTextString(m) }
func (*LoginGame) ProtoMessage()    {}
func (*LoginGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{1}
}

func (m *LoginGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginGame.Unmarshal(m, b)
}
func (m *LoginGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginGame.Marshal(b, m, deterministic)
}
func (m *LoginGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginGame.Merge(m, src)
}
func (m *LoginGame) XXX_Size() int {
	return xxx_messageInfo_LoginGame.Size(m)
}
func (m *LoginGame) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginGame.DiscardUnknown(m)
}

var xxx_messageInfo_LoginGame proto.InternalMessageInfo

func (m *LoginGame) GetAdid() string {
	if m != nil {
		return m.Adid
	}
	return ""
}

func (m *LoginGame) GetIdfv() string {
	if m != nil {
		return m.Idfv
	}
	return ""
}

func (m *LoginGame) GetAppsflyerId() string {
	if m != nil {
		return m.AppsflyerId
	}
	return ""
}

func (m *LoginGame) GetAdvertisingId() string {
	if m != nil {
		return m.AdvertisingId
	}
	return ""
}

func (m *LoginGame) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *LoginGame) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *LoginGame) GetReserved_2() string {
	if m != nil {
		return m.Reserved_2
	}
	return ""
}

func (m *LoginGame) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func (m *LoginGame) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *LoginGame) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginGame) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *LoginGame) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

// 防沉迷返回
type StateQueryResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrCode              string   `protobuf:"bytes,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	AuthenticationStatus int32    `protobuf:"varint,4,opt,name=authentication_status,json=authenticationStatus,proto3" json:"authentication_status,omitempty"`
	IsHoliday            bool     `protobuf:"varint,5,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	LeftGameTime         int32    `protobuf:"varint,8,opt,name=left_game_time,json=leftGameTime,proto3" json:"left_game_time,omitempty"`
	EachPayAmount        int32    `protobuf:"varint,9,opt,name=each_pay_amount,json=eachPayAmount,proto3" json:"each_pay_amount,omitempty"`
	LeftPayAmount        int32    `protobuf:"varint,10,opt,name=left_pay_amount,json=leftPayAmount,proto3" json:"left_pay_amount,omitempty"`
	LoginCode            int32    `protobuf:"varint,11,opt,name=login_code,json=loginCode,proto3" json:"login_code,omitempty"`
	LoginMessage         string   `protobuf:"bytes,12,opt,name=login_message,json=loginMessage,proto3" json:"login_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateQueryResponse) Reset()         { *m = StateQueryResponse{} }
func (m *StateQueryResponse) String() string { return proto.CompactTextString(m) }
func (*StateQueryResponse) ProtoMessage()    {}
func (*StateQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{2}
}

func (m *StateQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateQueryResponse.Unmarshal(m, b)
}
func (m *StateQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateQueryResponse.Marshal(b, m, deterministic)
}
func (m *StateQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateQueryResponse.Merge(m, src)
}
func (m *StateQueryResponse) XXX_Size() int {
	return xxx_messageInfo_StateQueryResponse.Size(m)
}
func (m *StateQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateQueryResponse proto.InternalMessageInfo

func (m *StateQueryResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *StateQueryResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *StateQueryResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *StateQueryResponse) GetAuthenticationStatus() int32 {
	if m != nil {
		return m.AuthenticationStatus
	}
	return 0
}

func (m *StateQueryResponse) GetIsHoliday() bool {
	if m != nil {
		return m.IsHoliday
	}
	return false
}

func (m *StateQueryResponse) GetLeftGameTime() int32 {
	if m != nil {
		return m.LeftGameTime
	}
	return 0
}

func (m *StateQueryResponse) GetEachPayAmount() int32 {
	if m != nil {
		return m.EachPayAmount
	}
	return 0
}

func (m *StateQueryResponse) GetLeftPayAmount() int32 {
	if m != nil {
		return m.LeftPayAmount
	}
	return 0
}

func (m *StateQueryResponse) GetLoginCode() int32 {
	if m != nil {
		return m.LoginCode
	}
	return 0
}

func (m *StateQueryResponse) GetLoginMessage() string {
	if m != nil {
		return m.LoginMessage
	}
	return ""
}

// extendData
type ExtendData struct {
	Nick                 string              `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Authentication       *StateQueryResponse `protobuf:"bytes,2,opt,name=authentication,proto3" json:"authentication,omitempty"`
	GameFirstLogin       bool                `protobuf:"varint,3,opt,name=game_first_login,json=gameFirstLogin,proto3" json:"game_first_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ExtendData) Reset()         { *m = ExtendData{} }
func (m *ExtendData) String() string { return proto.CompactTextString(m) }
func (*ExtendData) ProtoMessage()    {}
func (*ExtendData) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{3}
}

func (m *ExtendData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendData.Unmarshal(m, b)
}
func (m *ExtendData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendData.Marshal(b, m, deterministic)
}
func (m *ExtendData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendData.Merge(m, src)
}
func (m *ExtendData) XXX_Size() int {
	return xxx_messageInfo_ExtendData.Size(m)
}
func (m *ExtendData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendData.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendData proto.InternalMessageInfo

func (m *ExtendData) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *ExtendData) GetAuthentication() *StateQueryResponse {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *ExtendData) GetGameFirstLogin() bool {
	if m != nil {
		return m.GameFirstLogin
	}
	return false
}

//第三方登录请求
type ThirdLoginReq struct {
	ThirdPlat            string       `protobuf:"bytes,1,opt,name=third_plat,json=thirdPlat,proto3" json:"third_plat,omitempty"`
	ThirdUid             string       `protobuf:"bytes,2,opt,name=third_uid,json=thirdUid,proto3" json:"third_uid,omitempty"`
	ThirdToken           string       `protobuf:"bytes,3,opt,name=third_token,json=thirdToken,proto3" json:"third_token,omitempty"`
	AccessToken          string       `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Client               *LoginClient `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,6,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ThirdLoginReq) Reset()         { *m = ThirdLoginReq{} }
func (m *ThirdLoginReq) String() string { return proto.CompactTextString(m) }
func (*ThirdLoginReq) ProtoMessage()    {}
func (*ThirdLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{4}
}

func (m *ThirdLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdLoginReq.Unmarshal(m, b)
}
func (m *ThirdLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdLoginReq.Marshal(b, m, deterministic)
}
func (m *ThirdLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdLoginReq.Merge(m, src)
}
func (m *ThirdLoginReq) XXX_Size() int {
	return xxx_messageInfo_ThirdLoginReq.Size(m)
}
func (m *ThirdLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdLoginReq proto.InternalMessageInfo

func (m *ThirdLoginReq) GetThirdPlat() string {
	if m != nil {
		return m.ThirdPlat
	}
	return ""
}

func (m *ThirdLoginReq) GetThirdUid() string {
	if m != nil {
		return m.ThirdUid
	}
	return ""
}

func (m *ThirdLoginReq) GetThirdToken() string {
	if m != nil {
		return m.ThirdToken
	}
	return ""
}

func (m *ThirdLoginReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ThirdLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *ThirdLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//第三方登录返回
type ThridLoginRsp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string      `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	ThirdUid             string      `protobuf:"bytes,3,opt,name=third_uid,json=thirdUid,proto3" json:"third_uid,omitempty"`
	Errmsg               string      `protobuf:"bytes,4,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string      `protobuf:"bytes,5,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            int32       `protobuf:"varint,6,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	ExtendData           *ExtendData `protobuf:"bytes,7,opt,name=extend_data,json=extendData,proto3" json:"extend_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ThridLoginRsp) Reset()         { *m = ThridLoginRsp{} }
func (m *ThridLoginRsp) String() string { return proto.CompactTextString(m) }
func (*ThridLoginRsp) ProtoMessage()    {}
func (*ThridLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{5}
}

func (m *ThridLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThridLoginRsp.Unmarshal(m, b)
}
func (m *ThridLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThridLoginRsp.Marshal(b, m, deterministic)
}
func (m *ThridLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThridLoginRsp.Merge(m, src)
}
func (m *ThridLoginRsp) XXX_Size() int {
	return xxx_messageInfo_ThridLoginRsp.Size(m)
}
func (m *ThridLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ThridLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ThridLoginRsp proto.InternalMessageInfo

func (m *ThridLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ThridLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *ThridLoginRsp) GetThirdUid() string {
	if m != nil {
		return m.ThirdUid
	}
	return ""
}

func (m *ThridLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *ThridLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *ThridLoginRsp) GetDhAccount() int32 {
	if m != nil {
		return m.DhAccount
	}
	return 0
}

func (m *ThridLoginRsp) GetExtendData() *ExtendData {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

//手机验证码登录请求
type SmsLoginReq struct {
	Step                 string       `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Phone                string       `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Verifycode           string       `protobuf:"bytes,3,opt,name=verifycode,proto3" json:"verifycode,omitempty"`
	Client               *LoginClient `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,5,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SmsLoginReq) Reset()         { *m = SmsLoginReq{} }
func (m *SmsLoginReq) String() string { return proto.CompactTextString(m) }
func (*SmsLoginReq) ProtoMessage()    {}
func (*SmsLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{6}
}

func (m *SmsLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsLoginReq.Unmarshal(m, b)
}
func (m *SmsLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsLoginReq.Marshal(b, m, deterministic)
}
func (m *SmsLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsLoginReq.Merge(m, src)
}
func (m *SmsLoginReq) XXX_Size() int {
	return xxx_messageInfo_SmsLoginReq.Size(m)
}
func (m *SmsLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_SmsLoginReq proto.InternalMessageInfo

func (m *SmsLoginReq) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *SmsLoginReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SmsLoginReq) GetVerifycode() string {
	if m != nil {
		return m.Verifycode
	}
	return ""
}

func (m *SmsLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *SmsLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//手机验证码登录返回
type SmsLoginRsp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string      `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string      `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string      `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            int32       `protobuf:"varint,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	ExtendData           *ExtendData `protobuf:"bytes,6,opt,name=extend_data,json=extendData,proto3" json:"extend_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SmsLoginRsp) Reset()         { *m = SmsLoginRsp{} }
func (m *SmsLoginRsp) String() string { return proto.CompactTextString(m) }
func (*SmsLoginRsp) ProtoMessage()    {}
func (*SmsLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{7}
}

func (m *SmsLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsLoginRsp.Unmarshal(m, b)
}
func (m *SmsLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsLoginRsp.Marshal(b, m, deterministic)
}
func (m *SmsLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsLoginRsp.Merge(m, src)
}
func (m *SmsLoginRsp) XXX_Size() int {
	return xxx_messageInfo_SmsLoginRsp.Size(m)
}
func (m *SmsLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SmsLoginRsp proto.InternalMessageInfo

func (m *SmsLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SmsLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *SmsLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *SmsLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *SmsLoginRsp) GetDhAccount() int32 {
	if m != nil {
		return m.DhAccount
	}
	return 0
}

func (m *SmsLoginRsp) GetExtendData() *ExtendData {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

//游客登录请求参数
type VisitorLoginReq struct {
	Dhid                 string       `protobuf:"bytes,1,opt,name=dhid,proto3" json:"dhid,omitempty"`
	Client               *LoginClient `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VisitorLoginReq) Reset()         { *m = VisitorLoginReq{} }
func (m *VisitorLoginReq) String() string { return proto.CompactTextString(m) }
func (*VisitorLoginReq) ProtoMessage()    {}
func (*VisitorLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{8}
}

func (m *VisitorLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorLoginReq.Unmarshal(m, b)
}
func (m *VisitorLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorLoginReq.Marshal(b, m, deterministic)
}
func (m *VisitorLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorLoginReq.Merge(m, src)
}
func (m *VisitorLoginReq) XXX_Size() int {
	return xxx_messageInfo_VisitorLoginReq.Size(m)
}
func (m *VisitorLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorLoginReq proto.InternalMessageInfo

func (m *VisitorLoginReq) GetDhid() string {
	if m != nil {
		return m.Dhid
	}
	return ""
}

func (m *VisitorLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *VisitorLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//游客登录返回
type VisitorLoginRsp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string      `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string      `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string      `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            int32       `protobuf:"varint,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	Visitor              string      `protobuf:"bytes,6,opt,name=visitor,proto3" json:"visitor,omitempty"`
	ExtendData           *ExtendData `protobuf:"bytes,7,opt,name=extend_data,json=extendData,proto3" json:"extend_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VisitorLoginRsp) Reset()         { *m = VisitorLoginRsp{} }
func (m *VisitorLoginRsp) String() string { return proto.CompactTextString(m) }
func (*VisitorLoginRsp) ProtoMessage()    {}
func (*VisitorLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{9}
}

func (m *VisitorLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorLoginRsp.Unmarshal(m, b)
}
func (m *VisitorLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorLoginRsp.Marshal(b, m, deterministic)
}
func (m *VisitorLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorLoginRsp.Merge(m, src)
}
func (m *VisitorLoginRsp) XXX_Size() int {
	return xxx_messageInfo_VisitorLoginRsp.Size(m)
}
func (m *VisitorLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorLoginRsp proto.InternalMessageInfo

func (m *VisitorLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VisitorLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *VisitorLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *VisitorLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *VisitorLoginRsp) GetDhAccount() int32 {
	if m != nil {
		return m.DhAccount
	}
	return 0
}

func (m *VisitorLoginRsp) GetVisitor() string {
	if m != nil {
		return m.Visitor
	}
	return ""
}

func (m *VisitorLoginRsp) GetExtendData() *ExtendData {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

//Fast登录请求参数
type FastLoginReq struct {
	DhToken              string       `protobuf:"bytes,1,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Client               *LoginClient `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Game                 *LoginGame   `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FastLoginReq) Reset()         { *m = FastLoginReq{} }
func (m *FastLoginReq) String() string { return proto.CompactTextString(m) }
func (*FastLoginReq) ProtoMessage()    {}
func (*FastLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{10}
}

func (m *FastLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastLoginReq.Unmarshal(m, b)
}
func (m *FastLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastLoginReq.Marshal(b, m, deterministic)
}
func (m *FastLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastLoginReq.Merge(m, src)
}
func (m *FastLoginReq) XXX_Size() int {
	return xxx_messageInfo_FastLoginReq.Size(m)
}
func (m *FastLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FastLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_FastLoginReq proto.InternalMessageInfo

func (m *FastLoginReq) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *FastLoginReq) GetClient() *LoginClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *FastLoginReq) GetGame() *LoginGame {
	if m != nil {
		return m.Game
	}
	return nil
}

//Fast登录返回
type FastLoginRsp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string      `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string      `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string      `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            int32       `protobuf:"varint,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	ExtendData           *ExtendData `protobuf:"bytes,6,opt,name=extend_data,json=extendData,proto3" json:"extend_data,omitempty"`
	ThirdPlat            string      `protobuf:"bytes,7,opt,name=third_plat,json=thirdPlat,proto3" json:"third_plat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FastLoginRsp) Reset()         { *m = FastLoginRsp{} }
func (m *FastLoginRsp) String() string { return proto.CompactTextString(m) }
func (*FastLoginRsp) ProtoMessage()    {}
func (*FastLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{11}
}

func (m *FastLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastLoginRsp.Unmarshal(m, b)
}
func (m *FastLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastLoginRsp.Marshal(b, m, deterministic)
}
func (m *FastLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastLoginRsp.Merge(m, src)
}
func (m *FastLoginRsp) XXX_Size() int {
	return xxx_messageInfo_FastLoginRsp.Size(m)
}
func (m *FastLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FastLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FastLoginRsp proto.InternalMessageInfo

func (m *FastLoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FastLoginRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *FastLoginRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *FastLoginRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *FastLoginRsp) GetDhAccount() int32 {
	if m != nil {
		return m.DhAccount
	}
	return 0
}

func (m *FastLoginRsp) GetExtendData() *ExtendData {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

func (m *FastLoginRsp) GetThirdPlat() string {
	if m != nil {
		return m.ThirdPlat
	}
	return ""
}

//游客绑定申请
type VistorBindThridReq struct {
	Dhid                 string   `protobuf:"bytes,1,opt,name=dhid,proto3" json:"dhid,omitempty"`
	DhToken              string   `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	ThirdPlat            string   `protobuf:"bytes,3,opt,name=third_plat,json=thirdPlat,proto3" json:"third_plat,omitempty"`
	ThirdToken           string   `protobuf:"bytes,4,opt,name=third_token,json=thirdToken,proto3" json:"third_token,omitempty"`
	Visitor              string   `protobuf:"bytes,5,opt,name=visitor,proto3" json:"visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VistorBindThridReq) Reset()         { *m = VistorBindThridReq{} }
func (m *VistorBindThridReq) String() string { return proto.CompactTextString(m) }
func (*VistorBindThridReq) ProtoMessage()    {}
func (*VistorBindThridReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{12}
}

func (m *VistorBindThridReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VistorBindThridReq.Unmarshal(m, b)
}
func (m *VistorBindThridReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VistorBindThridReq.Marshal(b, m, deterministic)
}
func (m *VistorBindThridReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VistorBindThridReq.Merge(m, src)
}
func (m *VistorBindThridReq) XXX_Size() int {
	return xxx_messageInfo_VistorBindThridReq.Size(m)
}
func (m *VistorBindThridReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VistorBindThridReq.DiscardUnknown(m)
}

var xxx_messageInfo_VistorBindThridReq proto.InternalMessageInfo

func (m *VistorBindThridReq) GetDhid() string {
	if m != nil {
		return m.Dhid
	}
	return ""
}

func (m *VistorBindThridReq) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *VistorBindThridReq) GetThirdPlat() string {
	if m != nil {
		return m.ThirdPlat
	}
	return ""
}

func (m *VistorBindThridReq) GetThirdToken() string {
	if m != nil {
		return m.ThirdToken
	}
	return ""
}

func (m *VistorBindThridReq) GetVisitor() string {
	if m != nil {
		return m.Visitor
	}
	return ""
}

//游客绑定回复
type VistorBindThridRsp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DhToken              string      `protobuf:"bytes,2,opt,name=dh_token,json=dhToken,proto3" json:"dh_token,omitempty"`
	Errmsg               string      `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	SmId                 string      `protobuf:"bytes,4,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DhAccount            int32       `protobuf:"varint,5,opt,name=dh_account,json=dhAccount,proto3" json:"dh_account,omitempty"`
	ExtendData           *ExtendData `protobuf:"bytes,6,opt,name=extend_data,json=extendData,proto3" json:"extend_data,omitempty"`
	ThirdPlat            string      `protobuf:"bytes,7,opt,name=third_plat,json=thirdPlat,proto3" json:"third_plat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VistorBindThridRsp) Reset()         { *m = VistorBindThridRsp{} }
func (m *VistorBindThridRsp) String() string { return proto.CompactTextString(m) }
func (*VistorBindThridRsp) ProtoMessage()    {}
func (*VistorBindThridRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{13}
}

func (m *VistorBindThridRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VistorBindThridRsp.Unmarshal(m, b)
}
func (m *VistorBindThridRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VistorBindThridRsp.Marshal(b, m, deterministic)
}
func (m *VistorBindThridRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VistorBindThridRsp.Merge(m, src)
}
func (m *VistorBindThridRsp) XXX_Size() int {
	return xxx_messageInfo_VistorBindThridRsp.Size(m)
}
func (m *VistorBindThridRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VistorBindThridRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VistorBindThridRsp proto.InternalMessageInfo

func (m *VistorBindThridRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VistorBindThridRsp) GetDhToken() string {
	if m != nil {
		return m.DhToken
	}
	return ""
}

func (m *VistorBindThridRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *VistorBindThridRsp) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *VistorBindThridRsp) GetDhAccount() int32 {
	if m != nil {
		return m.DhAccount
	}
	return 0
}

func (m *VistorBindThridRsp) GetExtendData() *ExtendData {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

func (m *VistorBindThridRsp) GetThirdPlat() string {
	if m != nil {
		return m.ThirdPlat
	}
	return ""
}

//给GMP调用的moss接口
type QueryRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Bundleids            []string `protobuf:"bytes,2,rep,name=bundleids,proto3" json:"bundleids,omitempty"`
	LoginType            string   `protobuf:"bytes,3,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	PageNum              int32    `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{14}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *QueryRequest) GetBundleids() []string {
	if m != nil {
		return m.Bundleids
	}
	return nil
}

func (m *QueryRequest) GetLoginType() string {
	if m != nil {
		return m.LoginType
	}
	return ""
}

func (m *QueryRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type QueryResponse struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Count                int32          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Msg                  string         `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*AccountData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{15}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryResponse) GetData() []*AccountData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountData struct {
	XId                  int32       `protobuf:"varint,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	BundleId             string      `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Facebook             string      `protobuf:"bytes,3,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Ios                  string      `protobuf:"bytes,4,opt,name=ios,proto3" json:"ios,omitempty"`
	Google               string      `protobuf:"bytes,5,opt,name=google,proto3" json:"google,omitempty"`
	Phone                string      `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Create               *CreateData `protobuf:"bytes,7,opt,name=create,proto3" json:"create,omitempty"`
	Visitor              string      `protobuf:"bytes,8,opt,name=visitor,proto3" json:"visitor,omitempty"`
	LastLogin            int64       `protobuf:"varint,9,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AccountData) Reset()         { *m = AccountData{} }
func (m *AccountData) String() string { return proto.CompactTextString(m) }
func (*AccountData) ProtoMessage()    {}
func (*AccountData) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{16}
}

func (m *AccountData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountData.Unmarshal(m, b)
}
func (m *AccountData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountData.Marshal(b, m, deterministic)
}
func (m *AccountData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountData.Merge(m, src)
}
func (m *AccountData) XXX_Size() int {
	return xxx_messageInfo_AccountData.Size(m)
}
func (m *AccountData) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountData.DiscardUnknown(m)
}

var xxx_messageInfo_AccountData proto.InternalMessageInfo

func (m *AccountData) GetXId() int32 {
	if m != nil {
		return m.XId
	}
	return 0
}

func (m *AccountData) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func (m *AccountData) GetFacebook() string {
	if m != nil {
		return m.Facebook
	}
	return ""
}

func (m *AccountData) GetIos() string {
	if m != nil {
		return m.Ios
	}
	return ""
}

func (m *AccountData) GetGoogle() string {
	if m != nil {
		return m.Google
	}
	return ""
}

func (m *AccountData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AccountData) GetCreate() *CreateData {
	if m != nil {
		return m.Create
	}
	return nil
}

func (m *AccountData) GetVisitor() string {
	if m != nil {
		return m.Visitor
	}
	return ""
}

func (m *AccountData) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

type CreateData struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	SmId                 string   `protobuf:"bytes,3,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	BundleId             string   `protobuf:"bytes,4,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateData) Reset()         { *m = CreateData{} }
func (m *CreateData) String() string { return proto.CompactTextString(m) }
func (*CreateData) ProtoMessage()    {}
func (*CreateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{17}
}

func (m *CreateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateData.Unmarshal(m, b)
}
func (m *CreateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateData.Marshal(b, m, deterministic)
}
func (m *CreateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateData.Merge(m, src)
}
func (m *CreateData) XXX_Size() int {
	return xxx_messageInfo_CreateData.Size(m)
}
func (m *CreateData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateData proto.InternalMessageInfo

func (m *CreateData) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CreateData) GetSmId() string {
	if m != nil {
		return m.SmId
	}
	return ""
}

func (m *CreateData) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

//新查询接口,支持批量查账号
type QueryReq struct {
	Accounts             []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Bundleids            []string `protobuf:"bytes,2,rep,name=bundleids,proto3" json:"bundleids,omitempty"`
	LoginType            string   `protobuf:"bytes,3,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	PageNum              int32    `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{18}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *QueryReq) GetBundleids() []string {
	if m != nil {
		return m.Bundleids
	}
	return nil
}

func (m *QueryReq) GetLoginType() string {
	if m != nil {
		return m.LoginType
	}
	return ""
}

func (m *QueryReq) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type QueryRsp struct {
	Code                 int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Count                int32          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Msg                  string         `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*AccountData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryRsp) Reset()         { *m = QueryRsp{} }
func (m *QueryRsp) String() string { return proto.CompactTextString(m) }
func (*QueryRsp) ProtoMessage()    {}
func (*QueryRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{19}
}

func (m *QueryRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRsp.Unmarshal(m, b)
}
func (m *QueryRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRsp.Marshal(b, m, deterministic)
}
func (m *QueryRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRsp.Merge(m, src)
}
func (m *QueryRsp) XXX_Size() int {
	return xxx_messageInfo_QueryRsp.Size(m)
}
func (m *QueryRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRsp proto.InternalMessageInfo

func (m *QueryRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryRsp) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryRsp) GetData() []*AccountData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 第三方换绑手机
type ChangeBindReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Plat                 string   `protobuf:"bytes,3,opt,name=plat,proto3" json:"plat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeBindReq) Reset()         { *m = ChangeBindReq{} }
func (m *ChangeBindReq) String() string { return proto.CompactTextString(m) }
func (*ChangeBindReq) ProtoMessage()    {}
func (*ChangeBindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{20}
}

func (m *ChangeBindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeBindReq.Unmarshal(m, b)
}
func (m *ChangeBindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeBindReq.Marshal(b, m, deterministic)
}
func (m *ChangeBindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeBindReq.Merge(m, src)
}
func (m *ChangeBindReq) XXX_Size() int {
	return xxx_messageInfo_ChangeBindReq.Size(m)
}
func (m *ChangeBindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeBindReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeBindReq proto.InternalMessageInfo

func (m *ChangeBindReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ChangeBindReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ChangeBindReq) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

type ChangeBindRsp struct {
	Code                 int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *AccountData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChangeBindRsp) Reset()         { *m = ChangeBindRsp{} }
func (m *ChangeBindRsp) String() string { return proto.CompactTextString(m) }
func (*ChangeBindRsp) ProtoMessage()    {}
func (*ChangeBindRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_81471964e5a3cd05, []int{21}
}

func (m *ChangeBindRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeBindRsp.Unmarshal(m, b)
}
func (m *ChangeBindRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeBindRsp.Marshal(b, m, deterministic)
}
func (m *ChangeBindRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeBindRsp.Merge(m, src)
}
func (m *ChangeBindRsp) XXX_Size() int {
	return xxx_messageInfo_ChangeBindRsp.Size(m)
}
func (m *ChangeBindRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeBindRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeBindRsp proto.InternalMessageInfo

func (m *ChangeBindRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChangeBindRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ChangeBindRsp) GetData() *AccountData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginClient)(nil), "glogin.LoginClient")
	proto.RegisterType((*LoginGame)(nil), "glogin.LoginGame")
	proto.RegisterType((*StateQueryResponse)(nil), "glogin.StateQueryResponse")
	proto.RegisterType((*ExtendData)(nil), "glogin.ExtendData")
	proto.RegisterType((*ThirdLoginReq)(nil), "glogin.ThirdLoginReq")
	proto.RegisterType((*ThridLoginRsp)(nil), "glogin.ThridLoginRsp")
	proto.RegisterType((*SmsLoginReq)(nil), "glogin.SmsLoginReq")
	proto.RegisterType((*SmsLoginRsp)(nil), "glogin.SmsLoginRsp")
	proto.RegisterType((*VisitorLoginReq)(nil), "glogin.VisitorLoginReq")
	proto.RegisterType((*VisitorLoginRsp)(nil), "glogin.VisitorLoginRsp")
	proto.RegisterType((*FastLoginReq)(nil), "glogin.FastLoginReq")
	proto.RegisterType((*FastLoginRsp)(nil), "glogin.FastLoginRsp")
	proto.RegisterType((*VistorBindThridReq)(nil), "glogin.VistorBindThridReq")
	proto.RegisterType((*VistorBindThridRsp)(nil), "glogin.VistorBindThridRsp")
	proto.RegisterType((*QueryRequest)(nil), "glogin.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "glogin.QueryResponse")
	proto.RegisterType((*AccountData)(nil), "glogin.AccountData")
	proto.RegisterType((*CreateData)(nil), "glogin.CreateData")
	proto.RegisterType((*QueryReq)(nil), "glogin.QueryReq")
	proto.RegisterType((*QueryRsp)(nil), "glogin.QueryRsp")
	proto.RegisterType((*ChangeBindReq)(nil), "glogin.ChangeBindReq")
	proto.RegisterType((*ChangeBindRsp)(nil), "glogin.ChangeBindRsp")
}

func init() {
	proto.RegisterFile("glogin/glogin.proto", fileDescriptor_81471964e5a3cd05)
}

var fileDescriptor_81471964e5a3cd05 = []byte{
	// 1520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x4d, 0x8f, 0x1b, 0x45,
	0x13, 0xd6, 0xd8, 0xe3, 0xaf, 0xf2, 0x7e, 0xe4, 0xed, 0x6c, 0xde, 0x4c, 0xfc, 0xbe, 0x81, 0x60,
	0x08, 0x44, 0x20, 0x25, 0x92, 0x23, 0x2e, 0x20, 0x21, 0x25, 0x0b, 0x09, 0x16, 0xd9, 0x28, 0xcc,
	0x2e, 0x39, 0x32, 0xea, 0x9d, 0x6e, 0xdb, 0xad, 0xf5, 0x7c, 0x64, 0x7a, 0xbc, 0xe0, 0x48, 0xfc,
	0x05, 0xfe, 0x00, 0xe2, 0xc4, 0x91, 0x33, 0x47, 0x7e, 0x09, 0x20, 0x21, 0x71, 0xe1, 0x0f, 0x70,
	0xe3, 0x80, 0xaa, 0xba, 0x67, 0x3c, 0xe3, 0xfd, 0x20, 0x20, 0x50, 0x04, 0xa7, 0x74, 0x3f, 0x55,
	0xe3, 0xae, 0x7e, 0xea, 0xe9, 0xaa, 0xda, 0xc0, 0xc5, 0xe9, 0x3c, 0x99, 0xaa, 0xf8, 0x96, 0xf9,
	0xe7, 0x66, 0x9a, 0x25, 0x79, 0xc2, 0xda, 0x66, 0x37, 0xfc, 0xaa, 0x01, 0xfd, 0x07, 0xb8, 0xda,
	0x9d, 0x2b, 0x19, 0xe7, 0x8c, 0x81, 0xab, 0x22, 0xa9, 0x3c, 0xe7, 0x9a, 0x73, 0xa3, 0xe7, 0xd3,
	0x9a, 0x5d, 0x05, 0xe0, 0xb1, 0xc8, 0x12, 0x25, 0x02, 0x25, 0xbc, 0x06, 0x59, 0x7a, 0x16, 0x19,
	0x0b, 0xfc, 0x44, 0xcc, 0x94, 0xf0, 0x9a, 0xe6, 0x13, 0x5c, 0xb3, 0x17, 0xa1, 0x1f, 0xf1, 0x30,
	0xe0, 0x42, 0x64, 0x52, 0x6b, 0xcf, 0x25, 0x13, 0x44, 0x3c, 0xbc, 0x63, 0x10, 0xf6, 0x12, 0x6c,
	0x08, 0x79, 0xac, 0x42, 0x19, 0x44, 0x89, 0x90, 0x73, 0xaf, 0x45, 0x1e, 0x7d, 0x83, 0xed, 0x21,
	0x84, 0xc7, 0x0a, 0xf2, 0x88, 0x79, 0x24, 0xbd, 0xb6, 0x39, 0x96, 0x90, 0x87, 0x3c, 0x92, 0x68,
	0x4e, 0x74, 0x70, 0x2c, 0x33, 0xad, 0x92, 0xd8, 0xeb, 0x18, 0x73, 0xa2, 0x1f, 0x1b, 0x00, 0x0f,
	0x88, 0x65, 0xfe, 0x49, 0x92, 0x1d, 0x05, 0xf9, 0x32, 0x95, 0x5e, 0xd7, 0x1c, 0x60, 0xb1, 0x83,
	0x65, 0x2a, 0xd9, 0x16, 0x34, 0x54, 0xea, 0xf5, 0xc8, 0xd0, 0x50, 0x29, 0xf3, 0xa0, 0x13, 0x26,
	0x8b, 0x38, 0xcf, 0x96, 0x1e, 0x10, 0x58, 0x6c, 0x87, 0x3f, 0x37, 0xa0, 0x47, 0x2c, 0xdd, 0xc7,
	0x93, 0x19, 0xb8, 0x5c, 0x28, 0x51, 0x70, 0x84, 0x6b, 0xe2, 0x4d, 0x4c, 0x8e, 0x2d, 0x3b, 0xb4,
	0xc6, 0x10, 0x78, 0x9a, 0xea, 0xc9, 0x7c, 0x29, 0xb3, 0xa0, 0x24, 0xa8, 0x5f, 0x62, 0x63, 0xc1,
	0xae, 0xc3, 0x16, 0x17, 0xc7, 0x32, 0xcb, 0x95, 0x56, 0xf1, 0x14, 0x9d, 0x0c, 0x55, 0x9b, 0x15,
	0x74, 0x2c, 0x2a, 0x6c, 0xe5, 0xc9, 0x91, 0x8c, 0xeb, 0x6c, 0x1d, 0x20, 0xc4, 0x06, 0xd0, 0x9d,
	0xf3, 0x78, 0xba, 0xe0, 0xd3, 0x82, 0xab, 0x72, 0x8f, 0x54, 0x65, 0x52, 0xcb, 0xec, 0x58, 0x8a,
	0x60, 0x54, 0x50, 0x55, 0x20, 0x23, 0xf6, 0x3f, 0xe8, 0x1d, 0x2e, 0x62, 0x31, 0x97, 0x78, 0xbe,
	0xe1, 0xa9, 0x6b, 0x80, 0x31, 0x65, 0x92, 0xa7, 0x69, 0xc9, 0xb3, 0x61, 0x0b, 0x78, 0x9a, 0x16,
	0x44, 0x0f, 0xa0, 0x9b, 0xce, 0x79, 0x3e, 0x49, 0xb2, 0xc8, 0xd2, 0x56, 0xee, 0x89, 0xd1, 0x19,
	0x8f, 0x63, 0x39, 0xf7, 0xfa, 0x96, 0x51, 0xb3, 0x65, 0x97, 0xa1, 0x33, 0xe5, 0x91, 0x0c, 0x42,
	0xe1, 0x6d, 0x90, 0xa5, 0x8d, 0xdb, 0x5d, 0x31, 0xfc, 0xa5, 0x01, 0x6c, 0x3f, 0xe7, 0xb9, 0xfc,
	0x70, 0x21, 0xb3, 0xa5, 0x2f, 0x75, 0x9a, 0xc4, 0xda, 0x5e, 0xe1, 0xc9, 0x42, 0xea, 0x3c, 0x28,
	0x99, 0xef, 0x59, 0x64, 0x2c, 0xd8, 0x15, 0xe8, 0xca, 0x2c, 0x0b, 0xc2, 0x44, 0x48, 0x9b, 0x82,
	0x8e, 0xcc, 0xb2, 0xdd, 0x44, 0x48, 0x3c, 0x09, 0x4d, 0x91, 0x9e, 0xda, 0x04, 0xb4, 0x65, 0x96,
	0xed, 0xe9, 0x29, 0xbb, 0x0d, 0x97, 0xf8, 0x22, 0x9f, 0xc9, 0x38, 0x57, 0x21, 0xcf, 0x55, 0x12,
	0x07, 0x3a, 0xe7, 0xf9, 0xc2, 0xa8, 0xb5, 0xe5, 0xef, 0xd4, 0x8d, 0xfb, 0x64, 0xc3, 0x38, 0x94,
	0x0e, 0x66, 0xc9, 0x5c, 0x09, 0xbe, 0xa4, 0x3c, 0x74, 0xfd, 0x9e, 0xd2, 0xef, 0x1b, 0x80, 0xbd,
	0x02, 0x5b, 0x73, 0x39, 0xc9, 0x03, 0xba, 0x5b, 0xae, 0x22, 0xa3, 0xbb, 0x96, 0xbf, 0x81, 0x28,
	0x8a, 0xe7, 0x40, 0x45, 0x92, 0xbd, 0x0a, 0xdb, 0x92, 0x87, 0xb3, 0x20, 0xe5, 0xcb, 0x80, 0x47,
	0xa8, 0x31, 0xe2, 0xb5, 0xe5, 0x6f, 0x22, 0xfc, 0x88, 0x2f, 0xef, 0x10, 0x88, 0x7e, 0xf4, 0x6b,
	0x15, 0x3f, 0x30, 0x7e, 0x08, 0xaf, 0xfc, 0xae, 0x02, 0xd0, 0x6b, 0x36, 0xf7, 0xef, 0x93, 0x4b,
	0x8f, 0x10, 0x62, 0xe0, 0x65, 0xd8, 0x34, 0xe6, 0x48, 0x6a, 0x8d, 0xfa, 0x30, 0x8c, 0x6f, 0x10,
	0xb8, 0x67, 0xb0, 0xe1, 0xe7, 0x0e, 0xc0, 0x7b, 0x9f, 0xe6, 0x32, 0x16, 0xef, 0xf2, 0x9c, 0xa3,
	0x9e, 0x63, 0x15, 0x1e, 0x15, 0x1a, 0xc7, 0x35, 0xbb, 0x0b, 0x5b, 0x75, 0x4e, 0x88, 0xea, 0xfe,
	0x68, 0x70, 0xd3, 0x96, 0x96, 0x93, 0x79, 0xf3, 0xd7, 0xbe, 0x60, 0x37, 0xe0, 0x02, 0x71, 0x33,
	0x51, 0x99, 0xce, 0x03, 0xfa, 0x8c, 0xd2, 0xd2, 0xf5, 0xb7, 0x10, 0xbf, 0x87, 0x30, 0xbd, 0xb4,
	0xe1, 0x4f, 0x0e, 0x6c, 0x1e, 0xcc, 0x54, 0x26, 0x68, 0xeb, 0xcb, 0x27, 0x78, 0xcd, 0x1c, 0x81,
	0x00, 0xf5, 0x55, 0x68, 0x80, 0x90, 0x47, 0x73, 0x9e, 0xa3, 0x8c, 0x8d, 0x79, 0x51, 0x56, 0xa9,
	0x2e, 0x01, 0x1f, 0x99, 0x82, 0x64, 0x8c, 0xe6, 0x01, 0x19, 0x25, 0x98, 0x9f, 0x33, 0xef, 0x07,
	0x1f, 0x6b, 0x18, 0x4a, 0xad, 0xad, 0x87, 0x6b, 0x1f, 0x2b, 0x61, 0xc6, 0xe5, 0x0d, 0x68, 0x87,
	0x54, 0x25, 0x29, 0xef, 0xfd, 0xd1, 0xc5, 0xe2, 0xde, 0x95, 0x02, 0xea, 0x5b, 0x17, 0x76, 0x1d,
	0xdc, 0x69, 0x51, 0xb7, 0xfa, 0xa3, 0xff, 0xd4, 0x5c, 0x51, 0x08, 0x3e, 0x99, 0x87, 0xdf, 0xd3,
	0x2d, 0x33, 0x65, 0x6f, 0xa9, 0x53, 0x64, 0x9e, 0xd2, 0xe8, 0x50, 0x1a, 0x69, 0x8d, 0xf2, 0x16,
	0x33, 0x1b, 0x98, 0x95, 0xb7, 0x98, 0x99, 0xa0, 0x6a, 0xb7, 0x6e, 0xae, 0xdd, 0xfa, 0xbf, 0x80,
	0x62, 0x47, 0xe9, 0xbb, 0xa5, 0xf4, 0x23, 0x3d, 0x65, 0x17, 0xa1, 0xa5, 0x23, 0x7c, 0x48, 0xa6,
	0x90, 0xb8, 0x3a, 0x1a, 0x0b, 0xaa, 0xb7, 0xb3, 0x80, 0x87, 0x54, 0xf4, 0x28, 0xee, 0x96, 0xdf,
	0x13, 0xb3, 0x3b, 0x06, 0x60, 0xb7, 0xa1, 0x2f, 0x49, 0x1f, 0x81, 0xe0, 0x39, 0xa7, 0x2a, 0xd2,
	0x1f, 0xb1, 0xe2, 0x5e, 0x2b, 0xe9, 0xf8, 0x20, 0xcb, 0xf5, 0xf0, 0x6b, 0x07, 0xfa, 0xfb, 0x91,
	0x2e, 0x53, 0xc8, 0xc0, 0xd5, 0xb9, 0x4c, 0x0b, 0x59, 0xe1, 0x9a, 0xed, 0x40, 0x2b, 0x9d, 0x25,
	0x71, 0xf1, 0x70, 0xcd, 0x86, 0xbd, 0x00, 0x70, 0x2c, 0x33, 0x35, 0x59, 0x12, 0x19, 0x36, 0x5f,
	0x2b, 0xa4, 0x92, 0x0c, 0xf7, 0xd9, 0x93, 0xd1, 0x3a, 0x3f, 0x19, 0xdf, 0x56, 0xa3, 0xfd, 0xe3,
	0xa9, 0x58, 0xb1, 0xdd, 0x3c, 0x9d, 0x6d, 0xf7, 0x4c, 0xb6, 0x5b, 0xbf, 0xc3, 0x76, 0xfb, 0x99,
	0xd8, 0x5e, 0xc2, 0xf6, 0x63, 0xa5, 0x55, 0x9e, 0x64, 0x55, 0xc2, 0xa9, 0x39, 0x3b, 0x95, 0xe6,
	0xbc, 0xa2, 0xae, 0xf1, 0xec, 0xd4, 0x35, 0xcf, 0xa7, 0xee, 0x3b, 0x67, 0xed, 0xec, 0xe7, 0x4b,
	0x9f, 0x07, 0x9d, 0x63, 0x13, 0x8d, 0x6d, 0x86, 0xc5, 0xf6, 0xcf, 0xc9, 0xf8, 0x33, 0xd8, 0xb8,
	0xc7, 0x6d, 0x61, 0x42, 0x56, 0xab, 0xb7, 0x70, 0xea, 0xb7, 0xf8, 0x3b, 0xc8, 0xfd, 0xc1, 0xa9,
	0x9e, 0xff, 0xcf, 0x13, 0xe6, 0x5a, 0xe5, 0xee, 0xac, 0x55, 0xee, 0xe1, 0x97, 0x0e, 0xb0, 0xc7,
	0x4a, 0xe7, 0x49, 0x76, 0x57, 0xc5, 0x82, 0xca, 0xe1, 0x59, 0xda, 0x3d, 0xe7, 0x96, 0xf5, 0x43,
	0x9a, 0xeb, 0xed, 0x61, 0xad, 0x03, 0xb8, 0x27, 0x3a, 0x40, 0x45, 0x33, 0xad, 0x9a, 0x66, 0xb0,
	0x15, 0x9d, 0x88, 0xef, 0x5f, 0x99, 0x85, 0x0d, 0xdb, 0xbc, 0x69, 0xac, 0x42, 0x42, 0x8a, 0x00,
	0xac, 0xc8, 0xed, 0x96, 0xfd, 0xbf, 0x98, 0x18, 0x95, 0xd0, 0x5e, 0xe3, 0x5a, 0x13, 0x7f, 0xa8,
	0x04, 0x56, 0xe3, 0x08, 0x0d, 0xde, 0x36, 0x11, 0x84, 0xd0, 0xd8, 0x7d, 0x05, 0xba, 0x29, 0x9f,
	0xca, 0x20, 0x5e, 0x44, 0x76, 0xd4, 0xea, 0xe0, 0xfe, 0xe1, 0x22, 0xc2, 0x66, 0x46, 0x26, 0xad,
	0x9e, 0x4a, 0x7b, 0x69, 0xf2, 0xdd, 0x57, 0x4f, 0xe5, 0x30, 0x87, 0xcd, 0xfa, 0x4c, 0x78, 0x1a,
	0xff, 0x3b, 0xd0, 0x32, 0x11, 0x37, 0x08, 0x34, 0x1b, 0x76, 0x01, 0x9a, 0x2b, 0xde, 0x71, 0xc9,
	0x5e, 0x03, 0x97, 0x98, 0x73, 0xaf, 0x35, 0xab, 0x8f, 0xd4, 0xf2, 0x4b, 0xd4, 0x91, 0xc3, 0xf0,
	0x57, 0x07, 0xfa, 0x15, 0x94, 0x6d, 0x43, 0xb3, 0x98, 0x40, 0x5b, 0x7e, 0x63, 0x2c, 0xea, 0xd3,
	0x73, 0x63, 0x6d, 0x7a, 0x1e, 0x40, 0x77, 0xc2, 0x43, 0x79, 0x98, 0x24, 0x47, 0x45, 0x73, 0x2e,
	0xf6, 0x18, 0x94, 0x4a, 0x8a, 0xbf, 0x8d, 0x70, 0x89, 0x0a, 0x99, 0x26, 0xc9, 0x74, 0x2e, 0xad,
	0x00, 0xed, 0x6e, 0xd5, 0x21, 0xdb, 0xd5, 0x0e, 0xf9, 0x3a, 0xb4, 0xc3, 0x4c, 0xf2, 0x5c, 0xae,
	0x17, 0xb1, 0x5d, 0x42, 0xe9, 0x0e, 0xd6, 0xa3, 0xaa, 0xed, 0x6e, 0xbd, 0x1e, 0x62, 0xb2, 0x78,
	0x39, 0x8a, 0xe1, 0x18, 0xda, 0xf4, 0x7b, 0xf3, 0xa2, 0xd8, 0x0c, 0x0f, 0x01, 0x56, 0x3f, 0x67,
	0xff, 0x62, 0x72, 0xca, 0xbf, 0x98, 0x18, 0xb8, 0x34, 0xe4, 0x36, 0xe8, 0x33, 0x5a, 0xaf, 0xe4,
	0xdc, 0xac, 0xc8, 0xb9, 0x46, 0x92, 0x5b, 0x27, 0x69, 0xf8, 0x85, 0x03, 0xdd, 0x42, 0x78, 0xc8,
	0x98, 0x55, 0x99, 0xf6, 0x1c, 0x52, 0x56, 0xb9, 0x7f, 0x3e, 0xb2, 0x4b, 0x8a, 0xe0, 0xce, 0x78,
	0xf1, 0x7f, 0xb9, 0xe2, 0xf6, 0x61, 0x73, 0x77, 0xc6, 0xe3, 0xa9, 0xc4, 0x62, 0x83, 0x94, 0x9c,
	0xfd, 0x0e, 0x4f, 0x1f, 0x9d, 0x18, 0xb8, 0x95, 0x12, 0x48, 0xeb, 0xe1, 0xc7, 0xb5, 0x1f, 0x3d,
	0xe3, 0x2a, 0x36, 0xe8, 0xc6, 0x69, 0x41, 0x3b, 0xe7, 0x06, 0x3d, 0xfa, 0xd1, 0x81, 0x16, 0x29,
	0x86, 0xdd, 0x82, 0xe6, 0xfe, 0xde, 0x3e, 0x2b, 0x7d, 0x2b, 0xe3, 0xdf, 0xe0, 0x24, 0xa8, 0x53,
	0xf6, 0x26, 0xb4, 0x68, 0xce, 0x67, 0x97, 0x0a, 0x6b, 0x6d, 0xec, 0x1f, 0x54, 0xe0, 0xea, 0x9c,
	0xfc, 0x36, 0x74, 0xec, 0xc0, 0xc1, 0x2e, 0x17, 0x1e, 0x6b, 0xd3, 0xcf, 0xe0, 0x74, 0x83, 0x4e,
	0xd9, 0x08, 0x5c, 0x6c, 0xa8, 0x6c, 0xa7, 0x70, 0xa8, 0xb6, 0xf7, 0xc1, 0x29, 0xa8, 0x4e, 0x47,
	0x1f, 0x80, 0x8b, 0xe4, 0xb1, 0x5d, 0xe8, 0x99, 0x36, 0x80, 0x31, 0x0f, 0x2a, 0x27, 0xac, 0xf5,
	0xaf, 0xc1, 0x99, 0x36, 0x9d, 0x8e, 0xbe, 0x71, 0xa0, 0x79, 0x3f, 0x4a, 0xd9, 0x3b, 0xb0, 0xfd,
	0x20, 0xe1, 0xc2, 0x12, 0x3a, 0x8e, 0x27, 0xc9, 0x2a, 0xa6, 0x6a, 0x31, 0x5e, 0xb1, 0x50, 0xaf,
	0x81, 0x23, 0x5b, 0xb3, 0x8b, 0xc6, 0x70, 0x61, 0xfd, 0xe3, 0xc1, 0x1a, 0xa2, 0x53, 0xf6, 0x16,
	0xc0, 0x4a, 0x0b, 0x2b, 0xd6, 0x6b, 0xa2, 0x1b, 0x9c, 0x06, 0xeb, 0xf4, 0xb0, 0x4d, 0xff, 0x7d,
	0x74, 0xfb, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xac, 0x72, 0x8e, 0x55, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// This is a compile-time assertion to ensure that this generated file
// is compatible with the moss package it is being compiled against.
const _ = moss_rpc.SupportPackageIsVersion3

func SMS(in *SmsLoginReq, opts *global.CallOption) (*SmsLoginRsp, error) {
	out := new(SmsLoginRsp)
	err := client.Send("glogin.Login.SMS", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func Third(in *ThirdLoginReq, opts *global.CallOption) (*ThridLoginRsp, error) {
	out := new(ThridLoginRsp)
	err := client.Send("glogin.Login.Third", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func Visitor(in *VisitorLoginReq, opts *global.CallOption) (*VisitorLoginRsp, error) {
	out := new(VisitorLoginRsp)
	err := client.Send("glogin.Login.Visitor", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func Fast(in *FastLoginReq, opts *global.CallOption) (*FastLoginRsp, error) {
	out := new(FastLoginRsp)
	err := client.Send("glogin.Login.Fast", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	SMS(*SmsLoginReq) (*SmsLoginRsp, error)
	Third(*ThirdLoginReq) (*ThridLoginRsp, error)
	Visitor(*VisitorLoginReq) (*VisitorLoginRsp, error)
	Fast(*FastLoginReq) (*FastLoginRsp, error)
}

func RegisterLoginServer(s *moss_rpc.Server, srv LoginServer) {
	s.RegisterService(&Login_serviceDesc, srv)
}

func _Login_SMS_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(SmsLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).SMS(in)
}

func _Login_Third_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(ThirdLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).Third(in)
}

func _Login_Visitor_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(VisitorLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).Visitor(in)
}

func _Login_Fast_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(FastLoginReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(LoginServer).Fast(in)
}

var Login_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "glogin.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "SMS",
			Handler:    _Login_SMS_Handler,
		},
		{
			MethodName: "Third",
			Handler:    _Login_Third_Handler,
		},
		{
			MethodName: "Visitor",
			Handler:    _Login_Visitor_Handler,
		},
		{
			MethodName: "Fast",
			Handler:    _Login_Fast_Handler,
		},
	},
	Metadata: "glogin/glogin.proto",
}

func BindThird(in *VistorBindThridReq, opts *global.CallOption) (*VistorBindThridRsp, error) {
	out := new(VistorBindThridRsp)
	err := client.Send("glogin.Bind.BindThird", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BindServer is the server API for Bind service.
type BindServer interface {
	BindThird(*VistorBindThridReq) (*VistorBindThridRsp, error)
}

func RegisterBindServer(s *moss_rpc.Server, srv BindServer) {
	s.RegisterService(&Bind_serviceDesc, srv)
}

func _Bind_BindThird_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(VistorBindThridReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(BindServer).BindThird(in)
}

var Bind_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "glogin.Bind",
	HandlerType: (*BindServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "BindThird",
			Handler:    _Bind_BindThird_Handler,
		},
	},
	Metadata: "glogin/glogin.proto",
}

func LoadAccountInfo(in *QueryRequest, opts *global.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := client.Send("glogin.Gmp.LoadAccountInfo", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func QueryAccount(in *QueryReq, opts *global.CallOption) (*QueryRsp, error) {
	out := new(QueryRsp)
	err := client.Send("glogin.Gmp.QueryAccount", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func ChangeBind(in *ChangeBindReq, opts *global.CallOption) (*ChangeBindRsp, error) {
	out := new(ChangeBindRsp)
	err := client.Send("glogin.Gmp.ChangeBind", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GmpServer is the server API for Gmp service.
type GmpServer interface {
	LoadAccountInfo(*QueryRequest) (*QueryResponse, error)
	QueryAccount(*QueryReq) (*QueryRsp, error)
	ChangeBind(*ChangeBindReq) (*ChangeBindRsp, error)
}

func RegisterGmpServer(s *moss_rpc.Server, srv GmpServer) {
	s.RegisterService(&Gmp_serviceDesc, srv)
}

func _Gmp_LoadAccountInfo_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(GmpServer).LoadAccountInfo(in)
}

func _Gmp_QueryAccount_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(GmpServer).QueryAccount(in)
}

func _Gmp_ChangeBind_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(ChangeBindReq)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(GmpServer).ChangeBind(in)
}

var Gmp_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "glogin.Gmp",
	HandlerType: (*GmpServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "LoadAccountInfo",
			Handler:    _Gmp_LoadAccountInfo_Handler,
		},
		{
			MethodName: "QueryAccount",
			Handler:    _Gmp_QueryAccount_Handler,
		},
		{
			MethodName: "ChangeBind",
			Handler:    _Gmp_ChangeBind_Handler,
		},
	},
	Metadata: "glogin/glogin.proto",
}
