// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication/authentication.proto

package anti_authentication

import (
	context "context"
	fmt "fmt"
	client "git.dhgames.cn/svr_comm/gmoss/v3/client"
	global "git.dhgames.cn/svr_comm/gmoss/v3/global"
	moss_rpc "git.dhgames.cn/svr_comm/gmoss/v3/moss_rpc"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 实名信息认证
type CheckRequest struct {
	GameCd               string   `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PlayerInfo           string   `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	PlayerName           string   `protobuf:"bytes,4,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerId             string   `protobuf:"bytes,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{0}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *CheckRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CheckRequest) GetPlayerInfo() string {
	if m != nil {
		return m.PlayerInfo
	}
	return ""
}

func (m *CheckRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *CheckRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type CheckResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrCode              string   `protobuf:"bytes,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	CheckMsg             string   `protobuf:"bytes,4,opt,name=check_msg,json=checkMsg,proto3" json:"check_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{1}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CheckResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *CheckResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CheckResponse) GetCheckMsg() string {
	if m != nil {
		return m.CheckMsg
	}
	return ""
}

// 实名信息查询
type QueryRequest struct {
	GameCd               string   `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *QueryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrCode              string   `protobuf:"bytes,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	RealNamed            bool     `protobuf:"varint,4,opt,name=real_named,json=realNamed,proto3" json:"real_named,omitempty"`
	GrownUp              bool     `protobuf:"varint,5,opt,name=grown_up,json=grownUp,proto3" json:"grown_up,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *QueryResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *QueryResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *QueryResponse) GetRealNamed() bool {
	if m != nil {
		return m.RealNamed
	}
	return false
}

func (m *QueryResponse) GetGrownUp() bool {
	if m != nil {
		return m.GrownUp
	}
	return false
}

type StateQueryRequest struct {
	GameCd               string   `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateQueryRequest) Reset()         { *m = StateQueryRequest{} }
func (m *StateQueryRequest) String() string { return proto.CompactTextString(m) }
func (*StateQueryRequest) ProtoMessage()    {}
func (*StateQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{4}
}

func (m *StateQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateQueryRequest.Unmarshal(m, b)
}
func (m *StateQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateQueryRequest.Marshal(b, m, deterministic)
}
func (m *StateQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateQueryRequest.Merge(m, src)
}
func (m *StateQueryRequest) XXX_Size() int {
	return xxx_messageInfo_StateQueryRequest.Size(m)
}
func (m *StateQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateQueryRequest proto.InternalMessageInfo

func (m *StateQueryRequest) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *StateQueryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StateQueryRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type StateQueryResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrCode              string   `protobuf:"bytes,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	AuthenticationStatus int32    `protobuf:"varint,4,opt,name=authentication_status,json=authenticationStatus,proto3" json:"authentication_status,omitempty"`
	IsHoliday            bool     `protobuf:"varint,5,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	LeftGameTime         int32    `protobuf:"varint,8,opt,name=left_game_time,json=leftGameTime,proto3" json:"left_game_time,omitempty"`
	EachPayAmount        int32    `protobuf:"varint,9,opt,name=each_pay_amount,json=eachPayAmount,proto3" json:"each_pay_amount,omitempty"`
	LeftPayAmount        int32    `protobuf:"varint,10,opt,name=left_pay_amount,json=leftPayAmount,proto3" json:"left_pay_amount,omitempty"`
	LoginCode            int32    `protobuf:"varint,11,opt,name=login_code,json=loginCode,proto3" json:"login_code,omitempty"`
	LoginMessage         string   `protobuf:"bytes,12,opt,name=login_message,json=loginMessage,proto3" json:"login_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateQueryResponse) Reset()         { *m = StateQueryResponse{} }
func (m *StateQueryResponse) String() string { return proto.CompactTextString(m) }
func (*StateQueryResponse) ProtoMessage()    {}
func (*StateQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{5}
}

func (m *StateQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateQueryResponse.Unmarshal(m, b)
}
func (m *StateQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateQueryResponse.Marshal(b, m, deterministic)
}
func (m *StateQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateQueryResponse.Merge(m, src)
}
func (m *StateQueryResponse) XXX_Size() int {
	return xxx_messageInfo_StateQueryResponse.Size(m)
}
func (m *StateQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateQueryResponse proto.InternalMessageInfo

func (m *StateQueryResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *StateQueryResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *StateQueryResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *StateQueryResponse) GetAuthenticationStatus() int32 {
	if m != nil {
		return m.AuthenticationStatus
	}
	return 0
}

func (m *StateQueryResponse) GetIsHoliday() bool {
	if m != nil {
		return m.IsHoliday
	}
	return false
}

func (m *StateQueryResponse) GetLeftGameTime() int32 {
	if m != nil {
		return m.LeftGameTime
	}
	return 0
}

func (m *StateQueryResponse) GetEachPayAmount() int32 {
	if m != nil {
		return m.EachPayAmount
	}
	return 0
}

func (m *StateQueryResponse) GetLeftPayAmount() int32 {
	if m != nil {
		return m.LeftPayAmount
	}
	return 0
}

func (m *StateQueryResponse) GetLoginCode() int32 {
	if m != nil {
		return m.LoginCode
	}
	return 0
}

func (m *StateQueryResponse) GetLoginMessage() string {
	if m != nil {
		return m.LoginMessage
	}
	return ""
}

type R struct {
	GameCd               string   `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Accounts             []string `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	DeviceIds            []string `protobuf:"bytes,3,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *R) Reset()         { *m = R{} }
func (m *R) String() string { return proto.CompactTextString(m) }
func (*R) ProtoMessage()    {}
func (*R) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{6}
}

func (m *R) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R.Unmarshal(m, b)
}
func (m *R) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R.Marshal(b, m, deterministic)
}
func (m *R) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R.Merge(m, src)
}
func (m *R) XXX_Size() int {
	return xxx_messageInfo_R.Size(m)
}
func (m *R) XXX_DiscardUnknown() {
	xxx_messageInfo_R.DiscardUnknown(m)
}

var xxx_messageInfo_R proto.InternalMessageInfo

func (m *R) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *R) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *R) GetDeviceIds() []string {
	if m != nil {
		return m.DeviceIds
	}
	return nil
}

type Rs struct {
	GameCd               string   `protobuf:"bytes,1,opt,name=game_cd,json=gameCd,proto3" json:"game_cd,omitempty"`
	Accounts             []string `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	DeviceIds            []string `protobuf:"bytes,3,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rs) Reset()         { *m = Rs{} }
func (m *Rs) String() string { return proto.CompactTextString(m) }
func (*Rs) ProtoMessage()    {}
func (*Rs) Descriptor() ([]byte, []int) {
	return fileDescriptor_067dc6fa29e56c89, []int{7}
}

func (m *Rs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rs.Unmarshal(m, b)
}
func (m *Rs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rs.Marshal(b, m, deterministic)
}
func (m *Rs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rs.Merge(m, src)
}
func (m *Rs) XXX_Size() int {
	return xxx_messageInfo_Rs.Size(m)
}
func (m *Rs) XXX_DiscardUnknown() {
	xxx_messageInfo_Rs.DiscardUnknown(m)
}

var xxx_messageInfo_Rs proto.InternalMessageInfo

func (m *Rs) GetGameCd() string {
	if m != nil {
		return m.GameCd
	}
	return ""
}

func (m *Rs) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *Rs) GetDeviceIds() []string {
	if m != nil {
		return m.DeviceIds
	}
	return nil
}

func init() {
	proto.RegisterType((*CheckRequest)(nil), "anti_authentication.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "anti_authentication.CheckResponse")
	proto.RegisterType((*QueryRequest)(nil), "anti_authentication.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "anti_authentication.QueryResponse")
	proto.RegisterType((*StateQueryRequest)(nil), "anti_authentication.StateQueryRequest")
	proto.RegisterType((*StateQueryResponse)(nil), "anti_authentication.StateQueryResponse")
	proto.RegisterType((*R)(nil), "anti_authentication.r")
	proto.RegisterType((*Rs)(nil), "anti_authentication.rs")
}

func init() {
	proto.RegisterFile("authentication/authentication.proto", fileDescriptor_067dc6fa29e56c89)
}

var fileDescriptor_067dc6fa29e56c89 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0x33, 0xba, 0x25, 0x6f, 0xed, 0x10, 0x66, 0x88, 0x30, 0x34, 0x31, 0x32, 0x34, 0x38,
	0x0d, 0x89, 0x1d, 0x38, 0x4f, 0x3b, 0xc0, 0x0e, 0xad, 0xa0, 0x03, 0x01, 0x07, 0x14, 0x99, 0xf8,
	0x35, 0xb5, 0x48, 0xe2, 0x60, 0x3b, 0x43, 0x3d, 0xf1, 0x2f, 0x38, 0xf1, 0x33, 0xe1, 0x8e, 0xfc,
	0x92, 0xd2, 0x44, 0xac, 0x20, 0x90, 0x7a, 0xf4, 0xf7, 0x3e, 0x7f, 0xfe, 0xfc, 0xbd, 0xe7, 0x04,
	0x0e, 0x79, 0x65, 0x67, 0x58, 0x58, 0x99, 0x70, 0x2b, 0x55, 0xf1, 0xb8, 0xbb, 0x3c, 0x2e, 0xb5,
	0xb2, 0x8a, 0xdd, 0xe4, 0x85, 0x95, 0x71, 0xb7, 0x14, 0x7d, 0xed, 0xc1, 0xe0, 0x6c, 0x86, 0xc9,
	0xc7, 0x09, 0x7e, 0xaa, 0xd0, 0x58, 0x76, 0x1b, 0xb6, 0x52, 0x9e, 0x63, 0x9c, 0x88, 0xb0, 0x77,
	0xd0, 0x7b, 0x14, 0x4c, 0x36, 0xdd, 0xf2, 0x4c, 0xb0, 0x1d, 0xf0, 0xa4, 0x08, 0x3d, 0xc2, 0x3c,
	0x29, 0xd8, 0x3d, 0xd8, 0x2e, 0x33, 0x3e, 0x47, 0x1d, 0xcb, 0x62, 0xaa, 0xc2, 0x0d, 0x2a, 0x40,
	0x0d, 0x9d, 0x17, 0x53, 0xd5, 0x22, 0x14, 0x3c, 0xc7, 0xf0, 0x5a, 0x9b, 0x30, 0xe6, 0x39, 0xb2,
	0xbb, 0x10, 0x2c, 0x14, 0x44, 0xd8, 0xa7, 0xb2, 0xdf, 0xec, 0x17, 0xd1, 0x17, 0x18, 0x36, 0xbe,
	0x4c, 0xa9, 0x0a, 0x83, 0x6c, 0x1f, 0x40, 0xd7, 0x1e, 0x1d, 0xbd, 0xf6, 0x16, 0x34, 0xc8, 0xb9,
	0x60, 0x77, 0xc0, 0x47, 0xad, 0xe3, 0x44, 0x09, 0x6c, 0x4c, 0x6e, 0xa1, 0xd6, 0x67, 0x4a, 0xa0,
	0xbb, 0x92, 0x2b, 0xe5, 0x26, 0x6d, 0x5c, 0x6e, 0xa2, 0xd6, 0x23, 0x93, 0x3a, 0x03, 0x89, 0x3b,
	0x83, 0x4a, 0xb5, 0x3f, 0x9f, 0x80, 0x91, 0x49, 0xa3, 0xa7, 0x30, 0x78, 0x59, 0xa1, 0x9e, 0xff,
	0x6b, 0x30, 0xd1, 0xb7, 0x1e, 0x0c, 0x9b, 0x9d, 0xeb, 0xb3, 0x4e, 0x92, 0x3c, 0xa3, 0x68, 0x05,
	0x79, 0xf7, 0x9d, 0x24, 0xcf, 0x5c, 0xb2, 0x24, 0x99, 0x6a, 0xf5, 0xb9, 0x88, 0xab, 0x92, 0x92,
	0xf5, 0x27, 0x5b, 0xb4, 0x7e, 0x5d, 0x46, 0xef, 0xe0, 0xc6, 0x85, 0xe5, 0x16, 0xff, 0xeb, 0x72,
	0x2e, 0x32, 0x81, 0x97, 0x32, 0x41, 0x77, 0x93, 0xda, 0x92, 0x5f, 0x03, 0xe7, 0x22, 0xfa, 0xe1,
	0x01, 0x6b, 0x6b, 0xaf, 0xef, 0xfa, 0x27, 0x70, 0xab, 0x3b, 0xc8, 0xb1, 0xb1, 0xdc, 0x56, 0x86,
	0x92, 0xe8, 0x4f, 0x76, 0xbb, 0xc5, 0x0b, 0xaa, 0x39, 0x1f, 0xd2, 0xc4, 0x33, 0x95, 0x49, 0xc1,
	0xe7, 0x4d, 0x2c, 0x81, 0x34, 0xcf, 0x6b, 0x80, 0x3d, 0x80, 0x9d, 0x0c, 0xa7, 0x36, 0xa6, 0x20,
	0xac, 0xcc, 0x31, 0xf4, 0x49, 0x6c, 0xe0, 0xd0, 0x67, 0x3c, 0xc7, 0x57, 0x32, 0x47, 0x76, 0x04,
	0xd7, 0x91, 0x27, 0xb3, 0xb8, 0xe4, 0xf3, 0x98, 0xe7, 0xaa, 0x2a, 0x6c, 0x18, 0x10, 0x6d, 0xe8,
	0xe0, 0x17, 0x7c, 0x7e, 0x4a, 0xa0, 0xe3, 0x91, 0x5a, 0x8b, 0x07, 0x35, 0xcf, 0xc1, 0x4b, 0xde,
	0x3e, 0x40, 0xa6, 0x52, 0x59, 0xd4, 0xf7, 0xdf, 0x26, 0x4a, 0x40, 0x08, 0x25, 0x70, 0x08, 0xc3,
	0xba, 0x9c, 0xa3, 0x31, 0x3c, 0xc5, 0x70, 0x40, 0x39, 0x0c, 0x08, 0x1c, 0xd5, 0x58, 0xf4, 0x06,
	0x7a, 0x7a, 0x75, 0x0b, 0xf7, 0xc0, 0xe7, 0x49, 0xe2, 0x0e, 0x33, 0xa1, 0x77, 0xb0, 0xe1, 0x3a,
	0xb6, 0x58, 0xbb, 0xd3, 0x7f, 0xb5, 0xd3, 0x84, 0x1b, 0x54, 0x0d, 0x16, 0xfd, 0x34, 0xd1, 0x5b,
	0xf0, 0xb4, 0x59, 0x87, 0xf2, 0x93, 0xef, 0x1e, 0xec, 0x9e, 0x76, 0x9b, 0x84, 0xfa, 0x12, 0x35,
	0x1b, 0x43, 0x9f, 0xde, 0x3d, 0xbb, 0x7f, 0x7c, 0xc5, 0xf7, 0xea, 0xb8, 0xfd, 0xad, 0xda, 0x8b,
	0xfe, 0x44, 0x69, 0x86, 0x6f, 0x0c, 0x7d, 0x9a, 0xc6, 0x15, 0x7a, 0xed, 0x57, 0xb0, 0x42, 0xaf,
	0x3b, 0xcc, 0xef, 0x01, 0x96, 0x23, 0xce, 0x8e, 0xae, 0xdc, 0xf1, 0xdb, 0xfb, 0xda, 0x7b, 0xf8,
	0x57, 0xde, 0x52, 0xfe, 0xb4, 0x12, 0xd2, 0xae, 0x47, 0xfe, 0xc3, 0x26, 0xfd, 0x0a, 0x4e, 0x7e,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x28, 0xbf, 0x81, 0x24, 0x31, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// This is a compile-time assertion to ensure that this generated file
// is compatible with the moss package it is being compiled against.
const _ = moss_rpc.SupportPackageIsVersion3

func Check(in *CheckRequest, opts *global.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := client.Send("anti_authentication.AuthenticationServer.Check", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func Query(in *QueryRequest, opts *global.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := client.Send("anti_authentication.AuthenticationServer.Query", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func StateQuery(in *StateQueryRequest, opts *global.CallOption) (*StateQueryResponse, error) {
	out := new(StateQueryResponse)
	err := client.Send("anti_authentication.AuthenticationServer.StateQuery", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func AuditQuery(in *StateQueryRequest, opts *global.CallOption) (*StateQueryResponse, error) {
	out := new(StateQueryResponse)
	err := client.Send("anti_authentication.AuthenticationServer.AuditQuery", in, out, opts)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServerServer is the server API for AuthenticationServer service.
type AuthenticationServerServer interface {
	Check(*CheckRequest) (*CheckResponse, error)
	Query(*QueryRequest) (*QueryResponse, error)
	StateQuery(*StateQueryRequest) (*StateQueryResponse, error)
	AuditQuery(*StateQueryRequest) (*StateQueryResponse, error)
}

func RegisterAuthenticationServerServer(s *moss_rpc.Server, srv AuthenticationServerServer) {
	s.RegisterService(&AuthenticationServer_serviceDesc, srv)
}

func _AuthenticationServer_Check_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(AuthenticationServerServer).Check(in)
}

func _AuthenticationServer_Query_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(AuthenticationServerServer).Query(in)
}

func _AuthenticationServer_StateQuery_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(StateQueryRequest)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(AuthenticationServerServer).StateQuery(in)
}

func _AuthenticationServer_AuditQuery_Handler(srv interface{}, ctx context.Context, data []byte, dec func([]byte, interface{}) error) (interface{}, error) {
	in := new(StateQueryRequest)
	if err := dec(data, in); err != nil {
		return nil, err
	}
	return srv.(AuthenticationServerServer).AuditQuery(in)
}

var AuthenticationServer_serviceDesc = moss_rpc.ServiceDesc{
	ServiceName: "anti_authentication.AuthenticationServer",
	HandlerType: (*AuthenticationServerServer)(nil),
	Methods: []moss_rpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AuthenticationServer_Check_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AuthenticationServer_Query_Handler,
		},
		{
			MethodName: "StateQuery",
			Handler:    _AuthenticationServer_StateQuery_Handler,
		},
		{
			MethodName: "AuditQuery",
			Handler:    _AuthenticationServer_AuditQuery_Handler,
		},
	},
	Metadata: "authentication/authentication.proto",
}
